// GENERATED by devtests/cars-data/derive.js - do not edit by hand (node devtests/cars-data/derive.js).
// F1Drive - cars to choose from: the standard car plus the 11 cars of the 2026 Formula 1 grid.
// Data as of 2026-09-30, after round 15 (Azerbaijan GP). ESTIMATES derived from public data for a game,
// NOT official specifications. Sources, formula and limits: docs/cars-data-sources.md.
// Calibrated on the v5 reference car (F1.CAR_PERF of js/car.js = every multiplier 1).
//
// window.F1_CARS = [{
//   id,                  /^[a-z0-9_-]{1,24}$/; 'standard' first. The team ids are the F1DB constructor ids
//                        (tools/seasons-raw.json: '2026-' + id).
//   team,                display name: Traditional Chinese (Taiwan usage) + English; teamZh / teamEn = the two parts
//   car,                 chassis designation
//   pu, engine,          power-unit supplier, its designation
//   colour, colour2,     livery '#rrggbb': main body paint, second livery colour (sampled from official renders / photos)
//   colourTeam,          the team colour of F1's timing graphics (published; bright, for HUD / lists)
//   perf: { power, drag, downforce, grip, brake, traction, ersPower, ersHarvest },
//                        multipliers on the standard car, each within 0.95 .. 1.05: power -> POWER (W/kg),
//                        drag -> DRAG_K, downforce -> DOWNFORCE, grip -> LAT_BASE and LAT_MAX, brake -> BRAKE_BASE,
//                        traction -> TRACTION, ersPower -> ers.power, ersHarvest -> ers.harvest. A LOWER drag is better.
//   ratings: { topSpeed, accel, cornering, braking, ers },   0..100 for the menu bars, 50 = the standard car
//   note,                one line, Traditional Chinese
//   est: { lapPct, topKmh }   model estimate: lap time vs the standard car in % (negative = faster, mean of the
//                        15 circuits raced so far, no battery), top speed without battery in km/h
// }, ...]
(function (root) {
  'use strict';
  var CARS = [
    {
      id: 'standard', team: 'F1Drive', teamZh: 'F1Drive', teamEn: 'F1Drive', car: '標準賽車',
      pu: 'F1Drive', engine: '標準動力單元（1.6 L V6 渦輪混合動力）',
      colour: '#9AA0A6', colour2: '#2B2F36', colourTeam: '#C8CCD0',
      perf: { power: 1, drag: 1, downforce: 1, grip: 1, brake: 1, traction: 1, ersPower: 1, ersHarvest: 1 },
      ratings: { topSpeed: 50, accel: 50, cornering: 50, braking: 50, ers: 50 },
      note: '遊戲的基準車：所有倍率都是 1，速度約在 2026 年車隊的中位數。',
      est: { lapPct: 0, topKmh: 330 }
    },
    {
      id: 'mercedes', team: '賓士 Mercedes', teamZh: '賓士', teamEn: 'Mercedes', car: 'W17',
      pu: 'Mercedes', engine: 'Mercedes-AMG F1 M17 E Performance',
      colour: '#0F100F', colour2: '#BDBCBA', colourTeam: '#00D7B6',
      perf: { power: 1.0055, drag: 0.9961, downforce: 1.015, grip: 1.0095, brake: 1.011, traction: 1.0057, ersPower: 1.009, ersHarvest: 1.02 },
      ratings: { topSpeed: 62, accel: 69, cornering: 71, braking: 75, ers: 69 },
      note: '全能標竿：加速、煞車與電能管理都是全場最佳，彎道也是頂尖；真實弱點是起跑與可靠度。',
      est: { lapPct: -0.48, topKmh: 331 }
    },
    {
      id: 'ferrari', team: '法拉利 Ferrari', teamZh: '法拉利', teamEn: 'Ferrari', car: 'SF-26',
      pu: 'Ferrari', engine: 'Ferrari 067/6',
      colour: '#BB1320', colour2: '#DDDDDC', colourTeam: '#ED1131',
      perf: { power: 0.9978, drag: 0.9952, downforce: 1.0135, grip: 1.0098, brake: 1.0088, traction: 1.0014, ersPower: 0.9957, ersHarvest: 0.99 },
      ratings: { topSpeed: 53, accel: 59, cornering: 71, braking: 71, ers: 41 },
      note: '彎道頂尖、出彎俐落，但動力單元偏弱，長直線尾段會掉速。',
      est: { lapPct: -0.37, topKmh: 330.3 }
    },
    {
      id: 'mclaren', team: '麥拉倫 McLaren', teamZh: '麥拉倫', teamEn: 'McLaren', car: 'MCL40',
      pu: 'Mercedes', engine: 'Mercedes-AMG F1 M17 E Performance',
      colour: '#F4872C', colour2: '#141212', colourTeam: '#F47600',
      perf: { power: 1.0055, drag: 1.0111, downforce: 1.0126, grip: 1.0073, brake: 1.0088, traction: 1.0084, ersPower: 0.9957, ersHarvest: 1.01 },
      ratings: { topSpeed: 44, accel: 58, cornering: 67, braking: 74, ers: 54 },
      note: '彎道強，季中升級後拿下分站冠軍；但在同一具 Mercedes 動力中直線最慢，極速是前段班最低。',
      est: { lapPct: -0.35, topKmh: 329.4 }
    },
    {
      id: 'red-bull', team: '紅牛 Red Bull', teamZh: '紅牛', teamEn: 'Red Bull', car: 'RB22',
      pu: 'Red Bull Ford', engine: 'Red Bull Ford DM01',
      colour: '#051F94', colour2: '#D9131C', colourTeam: '#4781D7',
      perf: { power: 1.0019, drag: 1.0019, downforce: 1.0078, grip: 1.0068, brake: 1.0082, traction: 1.0042, ersPower: 1.0047, ersHarvest: 1 },
      ratings: { topSpeed: 50, accel: 58, cornering: 65, braking: 68, ers: 53 },
      note: '內燃機是 FIA 評定的基準（最強），但全季極速只在中位數；底盤難調，高速彎是前四強中最弱。',
      est: { lapPct: -0.29, topKmh: 330 }
    },
    {
      id: 'racing-bulls', team: '小紅牛 Racing Bulls', teamZh: '小紅牛', teamEn: 'Racing Bulls', car: 'VCARB 03',
      pu: 'Red Bull Ford', engine: 'Red Bull Ford DM01',
      colour: '#D6D6D5', colour2: '#08419E', colourTeam: '#6C98FF',
      perf: { power: 1.0019, drag: 0.9981, downforce: 0.9987, grip: 1.0008, brake: 1.0035, traction: 0.9992, ersPower: 1.0052, ersHarvest: 1 },
      ratings: { topSpeed: 55, accel: 50, cornering: 51, braking: 54, ers: 53 },
      note: '中段班最快：直線速度名列前茅（測速點全季平均僅次於 Alpine），彎道中規中矩、調校窗口窄。',
      est: { lapPct: -0.02, topKmh: 330.4 }
    },
    {
      id: 'alpine', team: 'Alpine', teamZh: 'Alpine', teamEn: 'Alpine', car: 'A526',
      pu: 'Mercedes', engine: 'Mercedes-AMG F1 M17 E Performance',
      colour: '#3190D5', colour2: '#EC6EAF', colourTeam: '#00A1E8',
      perf: { power: 1.0055, drag: 0.9891, downforce: 0.9971, grip: 0.9995, brake: 0.9993, traction: 0.997, ersPower: 1.0028, ersHarvest: 1.01 },
      ratings: { topSpeed: 70, accel: 56, cornering: 47, braking: 44, ers: 58 },
      note: '全場極速最高（Monza 桿位），但高速彎推頭、下壓力不足。',
      est: { lapPct: 0, topKmh: 331.8 }
    },
    {
      id: 'haas', team: '哈斯 Haas', teamZh: '哈斯', teamEn: 'Haas', car: 'VF-26',
      pu: 'Ferrari', engine: 'Ferrari 067/6',
      colour: '#D0D0CF', colour2: '#E51112', colourTeam: '#9C9FA2',
      perf: { power: 0.9978, drag: 0.9993, downforce: 0.9944, grip: 0.9958, brake: 0.9917, traction: 0.9987, ersPower: 0.9994, ersHarvest: 0.99 },
      ratings: { topSpeed: 48, accel: 48, cornering: 39, braking: 33, ers: 43 },
      note: '開季正賽表現亮眼，但全季進步幅度最小、單圈速度偏弱，慢彎入彎是弱點。',
      est: { lapPct: 0.18, topKmh: 329.8 }
    },
    {
      id: 'audi', team: '奧迪 Audi', teamZh: '奧迪', teamEn: 'Audi', car: 'R26',
      pu: 'Audi', engine: 'Audi AFR 26 Hybrid',
      colour: '#8F8881', colour2: '#EA0F06', colourTeam: '#F50537',
      perf: { power: 1.0015, drag: 1, downforce: 1.0027, grip: 0.9987, brake: 0.9975, traction: 0.9986, ersPower: 0.9995, ersHarvest: 0.98 },
      ratings: { topSpeed: 52, accel: 46, cornering: 49, braking: 48, ers: 37 },
      note: '底盤不錯，中高速彎是中段班最好的之一；自製動力單元能量管理較差、起跑吃虧。',
      est: { lapPct: 0.05, topKmh: 330.2 }
    },
    {
      id: 'williams', team: '威廉斯 Williams', teamZh: '威廉斯', teamEn: 'Williams', car: 'FW48',
      pu: 'Mercedes', engine: 'Mercedes-AMG F1 M17 E Performance',
      colour: '#0B33F2', colour2: '#27A3CF', colourTeam: '#1868DB',
      perf: { power: 1.0055, drag: 1.0036, downforce: 0.9899, grip: 0.9912, brake: 0.9893, traction: 0.9996, ersPower: 1.0055, ersHarvest: 1.01 },
      ratings: { topSpeed: 53, accel: 45, cornering: 28, braking: 28, ers: 60 },
      note: '開季超重又缺下壓力，彎道與煞車吃虧；靠 Mercedes 動力，直線速度仍在中位數以上。',
      est: { lapPct: 0.33, topKmh: 330.2 }
    },
    {
      id: 'aston-martin', team: '奧斯頓馬丁 Aston Martin', teamZh: '奧斯頓馬丁', teamEn: 'Aston Martin', car: 'AMR26',
      pu: 'Honda', engine: 'Honda RA626H',
      colour: '#0C5F49', colour2: '#D1CE48', colourTeam: '#229971',
      perf: { power: 0.9686, drag: 1, downforce: 0.983, grip: 0.9889, brake: 0.988, traction: 0.985, ersPower: 0.9708, ersHarvest: 0.97 },
      ratings: { topSpeed: 10, accel: 10, cornering: 19, braking: 21, ers: 12 },
      note: '被 Honda 動力單元拖累：極速、加速、電能都是全場最弱，慢彎相對沒那麼差。',
      est: { lapPct: 0.77, topKmh: 326.4 }
    },
    {
      id: 'cadillac', team: '凱迪拉克 Cadillac', teamZh: '凱迪拉克', teamEn: 'Cadillac', car: 'MAC-26',
      pu: 'Ferrari', engine: 'Ferrari 067/6',
      colour: '#DBDDDB', colour2: '#232327', colourTeam: '#909090',
      perf: { power: 0.9978, drag: 1.0055, downforce: 0.9779, grip: 0.9855, brake: 0.983, traction: 0.9946, ersPower: 0.9939, ersHarvest: 0.99 },
      ratings: { topSpeed: 41, accel: 29, cornering: 10, braking: 11, ers: 40 },
      note: '新車隊首作：平衡尚可但嚴重缺下壓力，三種彎都是全場最慢，極速略低於中位數。',
      est: { lapPct: 0.71, topKmh: 329.2 }
    }
  ];
  root.F1_CARS = CARS;
  if (typeof module !== 'undefined' && module.exports) module.exports = CARS;
})(typeof window !== 'undefined' ? window : globalThis);
