// F1Drive - the cars of every season: js/seasons-data.js (window.F1_SEASONS, generated by tools/build-cars.mjs) turned
// into CarSpec objects (js/README-interfaces.md, v6). Pure data lookup: no DOM, no THREE; loads before js/car.js.
//
//   F1.cars = {
//     seasons,               [{year, label, engine, count}] ascending (count = cars of that year incl. the standard car)
//     list(year) -> [CarSpec]   that season's cars, '<year>-standard' first; [] for a year that is not a season
//     get(id) -> CarSpec | null
//     resolve(id, year?) -> CarSpec   never null: the car itself when it is of that year; else the same team (lineage:
//                            Toro Rosso -> AlphaTauri -> RB -> Racing Bulls ...) in that year if it raced then; else that
//                            year's standard car. A bare constructor id ('mercedes', the ids of js/cars-data.js, or a
//                            lineage key) names that team; 'standard' the standard car. No / invalid year: the car's own
//                            year when the id is known, else DEFAULT_YEAR (so resolve('mercedes') -> '2026-mercedes').
//     DEFAULT_YEAR,          the newest season
//     attribution            { f1db, f1dbShort, sources2026, disclaimer } strings for the menu
//   }
// CarSpec = era value x the car's multiplier (clamped to 0.95..1.05) for power, dragK (drag), downforce, latBase and
// latMax (grip), brakeBase (brake), traction, ers.power (ersPower), ers.harvest (ersHarvest); everything else is the
// era's (ers.store, the 2026 ers.taperKmh, drivetrain, cockpit). The 2025 standard car is F1.REF_SPEC, number for
// number. Every number is checked with the ranges of js/car.js's F1.sanitizeSpec (physics 1/4..4 x the reference,
// ERS 1/10..10 x, gears 10..500 km/h, rpm, shift time, cylinders, the taper's speeds), the era value and again each
// era x multiplier product: a broken data file falls back to the v5 reference car's
// values, never to NaN, and every CarSpec is exactly what js/car.js drives (F1.sanitizeSpec(spec) deep-equals spec), so
// the HUD, the sound and the physics never disagree.
// The CarSpecs are built once and FROZEN (shared by every caller): copy before changing one.
// Security: ids and years arrive from the network. Lookups go through Map objects only (an id such as 'constructor'
// passes /^[a-z0-9-]{1,40}$/ and must never reach a plain object's prototype).
(function (root) {
  'use strict';
  var F1 = root.F1 = root.F1 || {};
  var ID_RE = /^[a-z0-9-]{1,40}$/, COLOUR_RE = /^#[0-9a-fA-F]{6}$/;
  var M_MIN = 0.95, M_MAX = 1.05;
  var RATINGS = ['topSpeed', 'accel', 'cornering', 'braking', 'ers'];
  var MULT = ['power', 'drag', 'downforce', 'grip', 'brake', 'traction', 'ersPower', 'ersHarvest'];
  var COCKPITS = ['modern', 'halo', 'halo18'];

  // The v5 reference car (js/car.js computes F1.REF_SPEC the same way): the fallback for anything missing or broken.
  var KMH = 1 / 3.6, TOP = 330 * KMH, DRAG_K = 0.0012, ROLL = 0.5;
  var POWER = (DRAG_K * TOP * TOP + ROLL) * TOP, ERS_POWER = 0.15 * POWER;
  var REF = {
    power: POWER, dragK: DRAG_K, downforce: 0.0045 / (20.0 / 9.81), latBase: 20.0, latMax: 44.0, brakeBase: 12.0,
    traction: 11.0, gearKmh: [60, 100, 140, 180, 220, 260, 300], topKmh: 345, rpmIdle: 4000, rpmShift: 11800,
    rpmMax: 15000, shiftTime: 0.05, cylinders: 6, aspiration: 'hybrid',
    ers: { store: 32 * ERS_POWER, power: ERS_POWER, harvest: 230 }, cockpit: 'halo18'
  };
  var STD = { team: 'F1Drive', teamZh: 'F1Drive', car: '標準賽車', engine: '1.6 L V6 渦輪混合動力', colour: '#9AA0A6', colour2: '#2B2F36' };

  function inRange(v, lo, hi) { return typeof v === 'number' && v >= lo && v <= hi; }      // (NaN fails)
  // js/car.js's F1.sanitizeSpec ranges: physics 1/4..4 x the reference, ERS 1/10..10 x; else the reference's value
  function phys(v, k) { return inRange(v, REF[k] / 4, REF[k] * 4) ? v : REF[k]; }
  function ersVal(v, k) { return inRange(v, REF.ers[k] / 10, REF.ers[k] * 10) ? v : REF.ers[k]; }
  function text(v, fb) { return typeof v === 'string' && v ? v.slice(0, 120) : fb; }
  function colour(v, fb) { return typeof v === 'string' && COLOUR_RE.test(v) ? v : fb; }
  function mult(m, k) { var v = m && typeof m === 'object' ? m[k] : 1; return typeof v === 'number' && isFinite(v) ? (v < M_MIN ? M_MIN : (v > M_MAX ? M_MAX : v)) : 1; }
  function own(o, k) { return o && typeof o === 'object' && Object.prototype.hasOwnProperty.call(o, k) ? o[k] : undefined; }

  // the era part (physics / drivetrain / ers / cockpit) of a season, every field checked as F1.sanitizeSpec does
  function cleanEra(e) {
    e = e && typeof e === 'object' ? e : {};
    var o = {}, k, i, v;
    var PH = ['power', 'dragK', 'downforce', 'latBase', 'latMax', 'brakeBase', 'traction'];
    for (i = 0; i < PH.length; i++) { k = PH[i]; o[k] = phys(own(e, k), k); }
    var g = own(e, 'gearKmh'), ok = Array.isArray(g) && g.length >= 1 && g.length <= 11;
    for (i = 0; ok && i < g.length; i++) if (!inRange(g[i], 10, 500) || (i > 0 && !(g[i] > g[i - 1]))) ok = false;
    o.gearKmh = ok ? g.slice() : REF.gearKmh.slice();
    var last = o.gearKmh[o.gearKmh.length - 1];
    v = own(e, 'topKmh');
    o.topKmh = inRange(v, last + 1, 600) ? v : (REF.topKmh > last + 1 ? REF.topKmh : Math.round(last * 1.15));
    v = own(e, 'rpmIdle'); o.rpmIdle = inRange(v, 500, 20000) ? v : REF.rpmIdle;
    v = own(e, 'rpmShift'); o.rpmShift = inRange(v, o.rpmIdle + 100, 25000) ? v : Math.max(REF.rpmShift, o.rpmIdle + 100);
    v = own(e, 'rpmMax'); o.rpmMax = inRange(v, o.rpmShift, 25000) ? v : Math.max(REF.rpmMax, o.rpmShift);
    v = own(e, 'shiftTime'); o.shiftTime = inRange(v, 0.01, 0.2) ? v : REF.shiftTime;
    var cy = own(e, 'cylinders');
    o.cylinders = inRange(cy, 2, 16) && cy % 2 === 0 ? cy : REF.cylinders;
    o.aspiration = own(e, 'aspiration') === 'na' ? 'na' : 'hybrid';
    var ers = own(e, 'ers');
    o.ers = ers === null || ers === false ? null : {
      store: ersVal(own(ers, 'store'), 'store'), power: ersVal(own(ers, 'power'), 'power'), harvest: ersVal(own(ers, 'harvest'), 'harvest')
    };
    // 2026: the deploy power fades out between [from, to] km/h (js/car.js's range); kept only when valid
    var tk = own(ers, 'taperKmh');
    if (o.ers && Array.isArray(tk) && tk.length === 2 && inRange(tk[0], 50, 599) && inRange(tk[1], tk[0] + 1, 600)) o.ers.taperKmh = [tk[0], tk[1]];
    o.cockpit = COCKPITS.indexOf(own(e, 'cockpit')) >= 0 ? e.cockpit : REF.cockpit;
    return o;
  }

  function freeze(s) {
    Object.freeze(s.ratings); Object.freeze(s.gearKmh);
    if (s.ers) { if (s.ers.taperKmh) Object.freeze(s.ers.taperKmh); Object.freeze(s.ers); }
    return Object.freeze(s);
  }

  // CarSpec of one car of a season: the era times the car's multipliers
  function makeSpec(year, era, c, isStd) {
    var m = own(c, 'perf'), r = own(c, 'ratings'), s = {}, i, k;
    s.id = c.id; s.year = year;
    s.team = text(own(c, 'team'), STD.team);
    s.teamZh = text(own(c, 'teamZh'), s.team);
    s.car = text(own(c, 'car'), STD.car);
    s.engine = text(own(c, 'engine'), isStd ? STD.engine : '');
    s.colour = colour(own(c, 'colour'), STD.colour);
    s.colour2 = colour(own(c, 'colour2'), STD.colour2);
    s.ratings = {};
    for (i = 0; i < RATINGS.length; i++) {
      k = RATINGS[i];
      var v = own(r, k);
      s.ratings[k] = typeof v === 'number' && v >= 0 && v <= 100 ? v : 50;
    }
    s.note = typeof own(c, 'note') === 'string' ? c.note.slice(0, 120) : '';
    // era x multiplier, the product checked again (an era value at the edge of the range x 1.05 would otherwise be
    // silently replaced by js/car.js)
    s.power = phys(era.power * mult(m, 'power'), 'power');
    s.dragK = phys(era.dragK * mult(m, 'drag'), 'dragK');
    s.downforce = phys(era.downforce * mult(m, 'downforce'), 'downforce');
    s.latBase = phys(era.latBase * mult(m, 'grip'), 'latBase');
    s.latMax = phys(era.latMax * mult(m, 'grip'), 'latMax');
    s.brakeBase = phys(era.brakeBase * mult(m, 'brake'), 'brakeBase');
    s.traction = phys(era.traction * mult(m, 'traction'), 'traction');
    s.gearKmh = era.gearKmh.slice();
    s.topKmh = era.topKmh; s.rpmIdle = era.rpmIdle; s.rpmShift = era.rpmShift; s.rpmMax = era.rpmMax;
    s.shiftTime = era.shiftTime;
    var cy = own(c, 'cylinders');
    s.cylinders = inRange(cy, 2, 16) && cy % 2 === 0 ? cy : era.cylinders;
    var asp = own(c, 'aspiration');
    s.aspiration = asp === 'na' || asp === 'hybrid' ? asp : era.aspiration;
    s.ers = era.ers ? { store: era.ers.store, power: ersVal(era.ers.power * mult(m, 'ersPower'), 'power'),
      harvest: ersVal(era.ers.harvest * mult(m, 'ersHarvest'), 'harvest') } : null;
    if (s.ers && era.ers.taperKmh) s.ers.taperKmh = era.ers.taperKmh.slice();
    s.cockpit = era.cockpit;
    return freeze(s);
  }

  var byId = new Map();              // id -> CarSpec
  var byYear = new Map();            // year -> [CarSpec], standard first
  var byLineage = new Map();         // lineage + '|' + year -> CarSpec
  var lineageOf = new Map();         // id -> lineage
  var alias = new Map();             // bare constructor id / lineage key -> lineage
  var seasons = [];

  var DATA = Array.isArray(root.F1_SEASONS) ? root.F1_SEASONS : [];
  for (var si = 0; si < DATA.length; si++) {
    var S = DATA[si];
    if (!S || typeof S !== 'object') continue;
    var year = S.year;
    if (typeof year !== 'number' || year % 1 !== 0 || year < 1950 || year > 2100 || byYear.has(year)) continue;
    var era = cleanEra(S.era), cars = Array.isArray(S.cars) ? S.cars : [], specs = [];
    var prefix = year + '-', stdId = year + '-standard';
    // the standard car first, whatever the file's order (made from the era when the file has none)
    var stdSrc = null, ci;
    for (ci = 0; ci < cars.length; ci++) if (cars[ci] && cars[ci].id === stdId) { stdSrc = cars[ci]; break; }
    var ordered = [stdSrc || { id: stdId, lineage: 'standard' }];
    for (ci = 0; ci < cars.length; ci++) if (cars[ci] && cars[ci] !== stdSrc) ordered.push(cars[ci]);
    for (ci = 0; ci < ordered.length; ci++) {
      var c = ordered[ci], id = c.id;
      if (typeof id !== 'string' || !ID_RE.test(id) || id.indexOf(prefix) !== 0 || id.length === prefix.length || byId.has(id)) continue;
      var isStd = id === stdId;
      var spec = makeSpec(year, era, isStd ? Object.assign({}, STD, c, { perf: null }) : c, isStd);
      var lin = isStd ? 'standard' : (typeof c.lineage === 'string' && ID_RE.test(c.lineage) ? c.lineage : id.slice(prefix.length));
      byId.set(id, spec);
      lineageOf.set(id, lin);
      if (!byLineage.has(lin + '|' + year)) byLineage.set(lin + '|' + year, spec);
      alias.set(id.slice(prefix.length), lin);                       // newer seasons overwrite: the current meaning wins
      if (!alias.has(lin)) alias.set(lin, lin);
      specs.push(spec);
    }
    byYear.set(year, specs);
    seasons.push(Object.freeze({ year: year, label: text(S.label, String(year)), engine: text(S.engine, ''), count: specs.length }));
  }
  seasons.sort(function (a, b) { return a.year - b.year; });
  var DEFAULT_YEAR = seasons.length ? seasons[seasons.length - 1].year : 2026;

  // nothing loaded at all: the reference car, so that resolve() still never returns null
  var FALLBACK = makeSpec(2025, cleanEra(REF), { id: '2025-standard' }, true);

  function toYear(y) {
    if (typeof y === 'string' && /^\d{4}$/.test(y)) y = +y;
    return typeof y === 'number' && byYear.has(y) ? y : null;
  }
  function get(id) {
    return typeof id === 'string' && ID_RE.test(id) ? (byId.get(id) || null) : null;
  }
  function list(year) {
    var y = toYear(year);
    return y === null ? [] : byYear.get(y).slice();
  }
  function resolve(id, year) {
    var y = toYear(year), known = get(id), lin = null;
    if (y === null) y = known ? known.year : (byYear.has(DEFAULT_YEAR) ? DEFAULT_YEAR : null);
    if (y === null) return FALLBACK;
    if (known && known.year === y) return known;
    if (known) lin = lineageOf.get(known.id);
    else if (typeof id === 'string' && ID_RE.test(id)) {
      var m = /^\d{4}-(.+)$/.exec(id);
      lin = alias.get(m ? m[1] : id) || null;
    }
    if (lin) {
      var hit = byLineage.get(lin + '|' + y);
      if (hit) return hit;
    }
    return byYear.get(y)[0] || FALLBACK;
  }

  var INFO = root.F1_SEASONS_INFO && typeof root.F1_SEASONS_INFO === 'object' ? root.F1_SEASONS_INFO : {};
  function info(k, fb) { var v = own(INFO, k); return typeof v === 'string' && v ? v.slice(0, 600) : fb; }
  F1.cars = {
    seasons: Object.freeze(seasons),
    list: list,
    get: get,
    resolve: resolve,
    DEFAULT_YEAR: DEFAULT_YEAR,
    attribution: Object.freeze({
      f1db: info('attribution', 'Formula 1 season data: F1DB (https://github.com/f1db/f1db), licensed under CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/); filtered, aggregated and in a few documented places corrected for F1Drive.'),
      f1dbShort: info('attributionShort', 'F1 data © F1DB (CC BY 4.0), modified'),
      sources2026: info('sources2026', '2026 cars: estimates from public data (FIA, formula1.com, OpenF1, Jolpica-F1, Autosport, team releases), see docs/cars-data-sources.md'),
      disclaimer: info('disclaimer', '車輛數據是依公開資料推估的遊戲數值，並非官方規格。')
    })
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = F1.cars;
})(typeof window !== 'undefined' ? window : globalThis);
