// node test/cars.test.js — the seasons data (js/seasons-data.js, generated by tools/build-cars.mjs) and its lookup
// (js/cars.js): data integrity, CarSpec shape, the resolve rules, the golden-rule anchor, robustness against broken
// data and hostile ids, and that the generated file is up to date (runs the generator with --check, ~20 s).
'use strict';
const assert = require('assert');
const path = require('path');
const fs = require('fs');
const vm = require('vm');
const { spawnSync } = require('child_process');
const ROOT = path.join(__dirname, '..');

global.window = global;
require(path.join(ROOT, 'js', 'seasons-data.js'));
require(path.join(ROOT, 'js', 'cars.js'));
require(path.join(ROOT, 'js', 'car.js'));            // after cars.js, as in index.html: F1.REF_SPEC, F1.sanitizeSpec
const F1 = global.F1, SEASONS = global.F1_SEASONS, INFO = global.F1_SEASONS_INFO;
const CARS26 = require(path.join(ROOT, 'js', 'cars-data.js'));
const RAW = JSON.parse(fs.readFileSync(path.join(ROOT, 'tools', 'seasons-raw.json'), 'utf8'));

let failed = 0;
function test(name, fn) {
  try { fn(); console.log('ok   ' + name); }
  catch (e) { failed++; console.log('FAIL ' + name + '\n     ' + (e && e.stack)); }
}
const ID_RE = /^[a-z0-9-]{1,40}$/, COLOUR_RE = /^#[0-9a-fA-F]{6}$/;
const MULT = ['power', 'drag', 'downforce', 'grip', 'brake', 'traction', 'ersPower', 'ersHarvest', 'ersStore'];
// the multiplier ranges (tools/build-cars.mjs CFG, js/cars.js): the battery's deploy / harvest and store are wider
const RANGE = k => k === 'ersStore' ? [0.9, 1.1] : (k === 'ersPower' || k === 'ersHarvest' ? [0.75, 1.15] : [0.95, 1.05]);
const ERS = JSON.parse(fs.readFileSync(path.join(ROOT, 'tools', 'ers-data.json'), 'utf8')).entries;
const LOG = JSON.parse(fs.readFileSync(path.join(ROOT, 'devtests', 'seasons-calib', 'entries.json'), 'utf8'));
const EFFECT = JSON.parse(fs.readFileSync(path.join(ROOT, 'devtests', 'seasons-calib', 'ers-effect.json'), 'utf8'));
// the cars that raced a whole season without KERS (docs/ers-data.md); 2010 had no battery at all
const NO_KERS = ['2011-lotus-racing', '2011-hrt', '2011-virgin', '2012-hrt', '2012-marussia'];
const RATINGS = ['topSpeed', 'accel', 'cornering', 'braking', 'ers'];
const PHYS = ['power', 'dragK', 'downforce', 'latBase', 'latMax', 'brakeBase', 'traction'];
const SPEC_KEYS = ['id', 'year', 'team', 'teamZh', 'car', 'engine', 'colour', 'colour2', 'ratings', 'note'].concat(PHYS)
  .concat(['gearKmh', 'topKmh', 'rpmIdle', 'rpmShift', 'rpmMax', 'shiftTime', 'cylinders', 'aspiration', 'ers', 'cockpit']);
const id = s => s && s.id;
const plain = x => JSON.parse(JSON.stringify(x));      // values from a vm sandbox (another realm's prototypes)

test('17 seasons 2010..2026, ascending, with label, engine and an era of finite numbers', () => {
  assert.strictEqual(SEASONS.length, 17);
  SEASONS.forEach((s, i) => {
    assert.strictEqual(s.year, 2010 + i);
    assert(typeof s.label === 'string' && s.label.indexOf(String(s.year)) === 0, 'label ' + s.label);
    assert(typeof s.engine === 'string' && s.engine.length > 3);
    for (const k of PHYS.concat(['topKmh', 'rpmIdle', 'rpmShift', 'rpmMax', 'shiftTime', 'cylinders'])) {
      assert(typeof s.era[k] === 'number' && isFinite(s.era[k]) && s.era[k] > 0, s.year + ' era.' + k + ' = ' + s.era[k]);
    }
    assert(Array.isArray(s.era.gearKmh) && s.era.gearKmh.every((g, j, a) => g > 0 && (j === 0 || g > a[j - 1])), 'gears');
    assert(s.era.topKmh > s.era.gearKmh[s.era.gearKmh.length - 1]);
    assert(s.era.rpmIdle < s.era.rpmShift && s.era.rpmShift <= s.era.rpmMax);
    assert(s.era.ers === null || PHYS.length && ['store', 'power', 'harvest'].every(k => s.era.ers[k] > 0 && isFinite(s.era.ers[k])));
    assert(['modern', 'halo', 'halo18'].includes(s.era.cockpit));
    assert(s.era.aspiration === 'na' || s.era.aspiration === 'hybrid');
  });
});

test('season labels describe their own year: no change of a later year is announced (2017 "...; 2018 起有 Halo")', () => {
  for (const s of SEASONS) {
    const text = s.label.slice(String(s.year).length);
    for (const m of text.match(/(19|20)\d\d/g) || []) assert(+m <= s.year, s.year + ' label names ' + m + ': ' + s.label);
  }
  assert.strictEqual(F1.cars.seasons.find(s => s.year === 2017).label, '2017 · 寬車寬胎高下壓力');
});

test('cars: standard first with every multiplier 1, ids unique and valid, colours, multipliers, ratings, texts', () => {
  const all = new Set();
  for (const s of SEASONS) {
    assert(s.cars.length >= 11, s.year + ': ' + s.cars.length + ' cars');
    const raw = RAW.seasons.find(r => r.year === s.year);
    assert.strictEqual(s.cars.length, raw.entries.length + 1, s.year + ': one car per F1DB entry + the standard car');
    s.cars.forEach((c, i) => {
      assert(ID_RE.test(c.id) && c.id.indexOf(s.year + '-') === 0, 'id ' + c.id);
      assert(!all.has(c.id), 'duplicate id ' + c.id);
      all.add(c.id);
      if (i === 0) {
        assert.strictEqual(c.id, s.year + '-standard');
        for (const k of MULT) assert.strictEqual(c.perf[k], 1, c.id + '.' + k);
        // 50 everywhere; the battery bar 0 in a season without a battery (2010)
        for (const k of RATINGS) assert.strictEqual(c.ratings[k], k === 'ers' && !s.era.ers ? 0 : 50, c.id + ' rating ' + k);
        assert.strictEqual(c.hasErs, !!s.era.ers, c.id + ' hasErs');
        assert.strictEqual(c.ersNote, '', c.id + ' ersNote');
      } else assert(raw.entries.some(e => e.id === c.id), c.id + ' is an F1DB entry');
      assert(COLOUR_RE.test(c.colour) && COLOUR_RE.test(c.colour2), c.id + ' colours ' + c.colour + ' ' + c.colour2);
      for (const k of MULT) assert(c.perf[k] >= RANGE(k)[0] && c.perf[k] <= RANGE(k)[1], c.id + '.' + k + ' = ' + c.perf[k]);
      for (const k of RATINGS) assert(Number.isInteger(c.ratings[k]) && c.ratings[k] >= 0 && c.ratings[k] <= 100, c.id + ' rating ' + k);
      for (const k of ['team', 'teamZh', 'car', 'engine']) assert(typeof c[k] === 'string' && c[k].length > 0 && c[k].length <= 120, c.id + '.' + k);
      assert(typeof c.note === 'string' && c.note.length <= 120, c.id + ' note');
      assert(typeof c.hasErs === 'boolean', c.id + ' hasErs');
      assert(typeof c.ersNote === 'string' && c.ersNote.length <= 120 && !/[\r\n]/.test(c.ersNote), c.id + ' ersNote');
      assert(ID_RE.test(c.lineage), c.id + ' lineage');
      assert(c.cylinders === s.era.cylinders && c.aspiration === s.era.aspiration, c.id + ' engine layout matches the era');
    });
  }
  assert.strictEqual(all.size, 17 + 180);
});

// the menu bars: 50 + 50 tanh(gain x / 50) (tools/build-cars.mjs ratingOf) never pins a car at 0 / 100, and keeps the
// order of the measured differences (devtests/seasons-calib/entries.json ratingX) inside every season
test('menu ratings are never pinned at 0 / 100 (the battery of a car without one is 0) and follow the order of the measured differences', () => {
  for (const s of SEASONS) {
    const ls = LOG.seasons.find(q => q.year === s.year);
    for (const c of s.cars) for (const k of RATINGS) {
      if (k === 'ers' && !c.hasErs) assert.strictEqual(c.ratings[k], 0, c.id + ' has no battery: its bar is 0');
      else assert(c.ratings[k] > 0 && c.ratings[k] < 100, c.id + ' rating ' + k + ' = ' + c.ratings[k]);
    }
    for (const k of RATINGS) {
      const rows = ls.cars.filter(c => c.ratingX[k] !== null).map(c => ({ id: c.id, x: c.ratingX[k], r: s.cars.find(q => q.id === c.id).ratings[k] })).sort((a, b) => a.x - b.x);
      for (let i = 1; i < rows.length; i++) assert(rows[i].r >= rows[i - 1].r, s.year + ' ' + k + ': ' + rows[i - 1].id + ' ' + rows[i - 1].r + ' > ' + rows[i].id + ' ' + rows[i].r);
    }
  }
  // the battery bar spreads over the range: the weakest (Honda 2015) low, the strongest (Mercedes 2014-16, Honda 2021) high
  const all = SEASONS.flatMap(s => s.cars.filter(c => c.hasErs)).map(c => c.ratings.ers);
  assert(Math.min(...all) <= 10 && Math.max(...all) >= 80, 'ers bar range ' + Math.min(...all) + '..' + Math.max(...all));
  // the 2010 back markers no longer share a 0 (their measured standing starts differ: HRT -7.1 %, Virgin -5.8 %)
  assert(F1.cars.get('2010-hrt').ratings.accel < F1.cars.get('2010-virgin').ratings.accel);
});

test('F1.cars.seasons / DEFAULT_YEAR / list', () => {
  assert.strictEqual(F1.cars.DEFAULT_YEAR, 2026);
  assert.strictEqual(F1.cars.seasons.length, 17);
  F1.cars.seasons.forEach((s, i) => {
    assert.strictEqual(s.year, 2010 + i);
    assert.strictEqual(s.label, SEASONS[i].label);
    assert.strictEqual(s.engine, SEASONS[i].engine);
    assert.strictEqual(s.count, F1.cars.list(s.year).length);
    assert.deepStrictEqual(F1.cars.list(s.year).map(id), SEASONS[i].cars.map(id));
  });
  assert.deepStrictEqual(F1.cars.list(2009), []);
  assert.deepStrictEqual(F1.cars.list('constructor'), []);
  assert.deepStrictEqual(F1.cars.list(null), []);
  assert.strictEqual(F1.cars.list('2014').length, F1.cars.list(2014).length, 'a 4-digit string year is accepted');
  const l = F1.cars.list(2014); l.pop();
  assert.strictEqual(F1.cars.list(2014).length, l.length + 1, 'list() returns a copy');
});

test('every CarSpec has exactly the contract fields, finite numbers, and js/car.js takes it unchanged', () => {
  for (const s of F1.cars.seasons) {
    for (const spec of F1.cars.list(s.year)) {
      assert.deepStrictEqual(Object.keys(spec).sort(), SPEC_KEYS.slice().sort(), spec.id + ' fields');
      assert.strictEqual(spec.year, s.year);
      for (const k of PHYS) assert(isFinite(spec[k]) && spec[k] > 0, spec.id + '.' + k);
      if (spec.ers) for (const k of ['store', 'power', 'harvest']) assert(isFinite(spec.ers[k]) && spec.ers[k] > 0, spec.id + '.ers.' + k);
      assert.deepStrictEqual(F1.sanitizeSpec(spec), spec, spec.id + ': F1.sanitizeSpec changes it');
      const p = F1.carPerf(spec);
      assert(isFinite(p.topSpeed) && p.topSpeed > 80 && p.topSpeed < 100, spec.id + ' top speed ' + p.topSpeed * 3.6);
      assert(Object.isFrozen(spec) && Object.isFrozen(spec.ratings) && Object.isFrozen(spec.gearKmh) && (!spec.ers || Object.isFrozen(spec.ers)), spec.id + ' frozen');
    }
  }
});

test('multipliers are applied to the era: CarSpec = era x perf', () => {
  const s = SEASONS.find(q => q.year === 2014), c = s.cars.find(q => q.id === '2014-mercedes'), spec = F1.cars.get('2014-mercedes');
  assert.strictEqual(spec.power, s.era.power * c.perf.power);
  assert.strictEqual(spec.dragK, s.era.dragK * c.perf.drag);
  assert.strictEqual(spec.downforce, s.era.downforce * c.perf.downforce);
  assert.strictEqual(spec.latBase, s.era.latBase * c.perf.grip);
  assert.strictEqual(spec.latMax, s.era.latMax * c.perf.grip);
  assert.strictEqual(spec.brakeBase, s.era.brakeBase * c.perf.brake);
  assert.strictEqual(spec.traction, s.era.traction * c.perf.traction);
  assert.strictEqual(spec.ers.power, s.era.ers.power * c.perf.ersPower);
  assert.strictEqual(spec.ers.harvest, s.era.ers.harvest * c.perf.ersHarvest);
  assert.strictEqual(spec.ers.store, s.era.ers.store * c.perf.ersStore);
  assert.strictEqual(c.perf.ersPower, 1.08, 'deploy from tools/ers-data.json');
  assert.strictEqual(c.perf.ersHarvest, 1.12, 'harvest from tools/ers-data.json');
  assert.strictEqual(spec.team, 'Mercedes');
  assert.strictEqual(spec.car, 'F1 W05 Hybrid');
});

test('golden rule anchor: the 2025 standard car deep-equals F1.REF_SPEC', () => {
  assert.deepStrictEqual(F1.cars.get('2025-standard'), F1.REF_SPEC);
  const e = SEASONS.find(q => q.year === 2025).era;
  for (const k of PHYS) assert(Object.is(e[k], F1.REF_SPEC[k]), 'era.' + k);
  assert.deepStrictEqual(e.ers, F1.REF_SPEC.ers);
});

test('era physics by the regulations: engines, gears, ERS, cockpit', () => {
  for (const s of SEASONS) {
    const y = s.year, e = s.era;
    assert.strictEqual(e.cylinders, y < 2014 ? 8 : 6, y + ' cylinders');
    assert.strictEqual(e.aspiration, y < 2014 ? 'na' : 'hybrid');
    assert.strictEqual(e.gearKmh.length + 1, y < 2014 ? 7 : 8, y + ' gears');
    if (y < 2014) assert.deepStrictEqual([e.rpmIdle, e.rpmShift, e.rpmMax], [4500, 17800, 18000], y + ' V8 rpm');
    else assert.strictEqual(e.rpmMax, y === 2025 ? F1.REF_SPEC.rpmMax : 15000, y + ' V6 rpm max');
    assert(e.shiftTime >= 0.03 && e.shiftTime <= 0.06);
    assert.strictEqual(e.cockpit, y <= 2017 ? 'modern' : (y <= 2021 ? 'halo' : 'halo18'), y + ' cockpit');
    if (y === 2010) assert.strictEqual(e.ers, null);
    else if (y <= 2013) {
      assert(e.ers.power < F1.REF_SPEC.ers.power * 0.7 && e.ers.store < F1.REF_SPEC.ers.store * 0.2, y + ' KERS 60 kW / 400 kJ');
      assert(Math.abs(e.ers.store / e.ers.power - 6.67) < 0.5, y + ' KERS lasts about 6.7 s: ' + e.ers.store / e.ers.power);
    } else if (y <= 2025) assert.deepStrictEqual(e.ers, F1.REF_SPEC.ers, y + ' ERS = the reference');
    else {
      assert(e.ers.power > 2.9 * F1.REF_SPEC.ers.power && e.ers.harvest > 5 * F1.REF_SPEC.ers.harvest, '2026 350 kW');
      assert.deepStrictEqual(e.ers.taperKmh, [290, 345], '2026: the deploy power fades out between 290 and 345 km/h (FIA C5.2.8)');
    }
    if (y < 2026 && e.ers) assert(!('taperKmh' in e.ers), y + ': no taper before 2026');
  }
  const top = y => F1.carPerf(F1.cars.get(y + '-standard')).topSpeed * 3.6;
  assert(top(2014) > top(2013) + 10, '2014 low drag: faster on the straights than the V8 + KERS cars');
  const e = y => SEASONS.find(q => q.year === y).era;
  assert(e(2014).downforce < e(2013).downforce, '2014 less downforce than 2013');
  for (const y of [2017, 2018, 2019, 2020, 2021]) assert(e(y).downforce > e(2025).downforce, y + ' high downforce');
  assert(e(2021).downforce < e(2020).downforce, '2021 floor cut');
  assert(e(2026).downforce < e(2025).downforce * 0.85 && e(2026).traction > e(2025).traction, '2026 less downforce, more electric power out of corners');
});

// review finding S1: with E held the 2026 car reached 377 km/h (boost top 381) against a real 338 km/h Monza trap and
// 345 km/h for 2025; the FIA's power-vs-speed rule gives it no electric power from 345 km/h
test('2026 battery: deploying all the way, every 2026 car tops out at 345 km/h at most and the standard car below 2025', () => {
  const top = spec => F1.carPerf(spec).topSpeedBoost * 3.6;
  for (const spec of F1.cars.list(2026)) assert(top(spec) <= 345, spec.id + ' boost top ' + top(spec).toFixed(1) + ' km/h');
  assert(top(F1.cars.get('2026-standard')) < top(F1.cars.get('2025-standard')), '2026 slower than 2025 at the end of a long straight');
  assert(top(F1.cars.get('2026-standard')) > F1.carPerf(F1.cars.get('2026-standard')).topSpeed * 3.6 + 3, 'the battery still adds speed below 345 km/h');
});

const LIVERIES = Object.assign({}, ...['2010-2017.json', '2018-2026.json'].map(f =>
  JSON.parse(fs.readFileSync(path.join(ROOT, 'tools', 'liveries', f), 'utf8')).entries));

// v6.1: the battery is tools/ers-data.json's (it replaces js/cars-data.js's ersPower / ersHarvest), and one chassis level L
// on js/cars-data.js's downforce / grip / brake / traction keeps the car's pace with it; power and drag are untouched
test('the 2026 cars are js/cars-data.js (power, drag, chassis + one level, notes, colours, names; Chinese name from the livery files)', () => {
  const s = SEASONS.find(q => q.year === 2026);
  for (const c of CARS26) {
    if (c.id === 'standard') continue;
    const d = s.cars.find(q => q.id === '2026-' + c.id);
    assert(d, '2026-' + c.id);
    assert.strictEqual(d.perf.power, c.perf.power, c.id + ' power');
    assert.strictEqual(d.perf.drag, c.perf.drag, c.id + ' drag');
    const L = ['downforce', 'grip', 'brake', 'traction'].map(k => d.perf[k] - c.perf[k]);
    assert(Math.max(...L) - Math.min(...L) <= 1.0001e-4, c.id + ': one level on the four chassis multipliers ' + L.join(' '));
    const e = ERS[d.id];
    assert.strictEqual(d.perf.ersPower, e.deploy, c.id + ' deploy');
    assert.strictEqual(d.perf.ersHarvest, c.id === 'mercedes' ? 1.0502 : e.harvest, c.id + ' harvest (Mercedes 1.08 cut to the F1.sanitizeSpec ceiling)');
    assert.strictEqual(d.perf.ersStore, e.store, c.id + ' store');
    assert.strictEqual(d.note, c.note);
    assert.strictEqual(d.colour, c.colour);
    assert.strictEqual(d.colour2, c.colour2);
    assert.strictEqual(d.team, c.teamEn);
    assert.strictEqual(d.teamZh, LIVERIES[d.id].teamZh || c.teamZh, d.id + ' teamZh: the fact-checked livery name');
    assert.strictEqual(d.car, c.id === 'mercedes' ? 'F1 W17 E Performance' : c.car);
  }
});

// ---- v6.1: every car's own battery (tools/ers-data.json, docs/ers-data.md) ----------------------------------------------
test('per-car battery: the five cars that raced without KERS (and all of 2010) have ers null, every other car its own', () => {
  const none = [];
  for (const s of SEASONS) for (const c of s.cars) {
    const spec = F1.cars.get(c.id);
    assert.strictEqual(spec.ers === null, !c.hasErs, c.id + ': CarSpec.ers null <=> hasErs false');
    if (!c.hasErs) { none.push(c.id); assert.strictEqual(spec.ratings.ers, 0, c.id + ' battery bar 0'); }
    if (s.year === 2010) { assert.strictEqual(spec.ers, null, c.id); continue; }
    if (c.id.endsWith('-standard')) { assert.deepStrictEqual(plain(spec.ers), plain(s.era.ers), c.id + ': the era battery'); continue; }
    const e = ERS[c.id];
    assert(e, c.id + ' is in tools/ers-data.json');
    assert.strictEqual(c.hasErs, e.hasErs !== false, c.id + ' hasErs');
    assert.strictEqual(c.ersNote, e.note, c.id + ' ersNote = the data note');
    assert.strictEqual(F1.cars.ersNote(c.id), e.note, c.id + ' F1.cars.ersNote');
    if (c.hasErs) {
      assert.strictEqual(c.perf.ersPower, e.deploy, c.id + ' deploy');
      if (c.id !== '2026-mercedes') assert.strictEqual(c.perf.ersHarvest, e.harvest, c.id + ' harvest');
      assert.strictEqual(c.perf.ersStore, e.store, c.id + ' store');
      assert(spec.ers.power === s.era.ers.power * c.perf.ersPower && spec.ers.harvest === s.era.ers.harvest * c.perf.ersHarvest &&
        spec.ers.store === s.era.ers.store * c.perf.ersStore, c.id + ': era x multiplier');
    }
  }
  assert.deepStrictEqual(none.filter(id => !/^2010-/.test(id)).sort(), NO_KERS.slice().sort());
  assert.strictEqual(none.filter(id => /^2010-/.test(id)).length, 13, '2010: no battery for anybody (12 cars + the standard car)');
  // 2013: everybody had KERS (Marussia's first, Caterham's Red Bull system)
  for (const spec of F1.cars.list(2013)) assert(spec.ers, spec.id);
  // the notes the menu can show: one line, non-empty where the data has one
  assert(SEASONS.flatMap(s => s.cars).filter(c => c.ersNote).length >= 100);
  for (const bad of ['constructor', '__proto__', 'toString', '', null, undefined, 5, {}, '2014-standard', '2010-red-bull', 'nope']) assert.strictEqual(F1.cars.ersNote(bad), '', String(bad));
});

test('battery multipliers stay in their ranges (deploy / harvest 0.75..1.15, store 0.9..1.1) and inside js/car.js\'s window', () => {
  const R = F1.REF_SPEC.ers;
  let lo = Infinity, hi = -Infinity;
  for (const s of SEASONS) for (const c of s.cars) {
    for (const k of ['ersPower', 'ersHarvest']) { assert(c.perf[k] >= 0.75 && c.perf[k] <= 1.15, c.id + '.' + k); lo = Math.min(lo, c.perf[k]); hi = Math.max(hi, c.perf[k]); }
    assert(c.perf.ersStore >= 0.9 && c.perf.ersStore <= 1.1, c.id + '.ersStore');
    const spec = F1.cars.get(c.id);
    if (spec.ers) for (const k of ['store', 'power', 'harvest']) assert(spec.ers[k] >= R[k] / 10 && spec.ers[k] <= R[k] * 10, c.id + '.ers.' + k);
  }
  assert(lo <= 0.8 && hi >= 1.1, 'the per-car batteries use the wider range: ' + lo + '..' + hi);
  // 2026's harvest sits at the window's ceiling / 1.05: Mercedes' 1.08 is cut to 1.0502, not dropped to the reference's
  assert(F1.cars.get('2026-mercedes').ers.harvest <= R.harvest * 10 && F1.cars.get('2026-mercedes').ers.harvest > F1.cars.get('2026-mclaren').ers.harvest);
});

test('battery order: 2014 Mercedes > 2014 Renault (Red Bull) > 2015 Honda (McLaren) in deploy and in harvest; 2021 Honda the strongest', () => {
  const g = id => F1.cars.get(id);
  for (const k of ['power', 'harvest']) {
    assert(g('2014-mercedes').ers[k] > g('2014-red-bull').ers[k] && g('2014-red-bull').ers[k] > g('2015-mclaren').ers[k], k);
    assert(g('2014-williams').ers[k] === g('2014-mercedes').ers[k], k + ': customers get the supplier\'s battery');
    assert(g('2014-ferrari').ers[k] === g('2014-standard').ers[k], k + ': Ferrari 2014 neutral');
  }
  assert(g('2014-mercedes').ratings.ers > g('2014-ferrari').ratings.ers && g('2014-ferrari').ratings.ers > g('2014-red-bull').ratings.ers && g('2014-red-bull').ratings.ers > g('2015-mclaren').ratings.ers);
  assert(g('2021-red-bull').ers.power > g('2021-mercedes').ers.power, '2021: Honda deploys best');
  assert(g('2026-aston-martin').ers.power < g('2026-standard').ers.power && g('2026-aston-martin').ratings.ers < g('2026-audi').ratings.ers);
});

// the lap-time targets hold WITH the battery deployed: the chassis level absorbs the battery's driven effect
test('pace with the battery: every car on its target, the battery effect absorbed by the chassis level (entries.json, ers-effect.json)', () => {
  for (const ls of LOG.seasons) {
    const s = SEASONS.find(q => q.year === ls.year);
    for (const c of ls.cars) {
      const d = s.cars.find(q => q.id === c.id), k = c.battery.key;
      assert(Math.abs(c.lapPct - c.targetPct) <= 0.01, c.id + ': ' + c.lapPct + ' vs target ' + c.targetPct);
      assert(Math.abs(c.profilePct + c.ersPct - c.lapPct) < 2e-4, c.id + ': lap = profile + battery');
      const fx = k === null ? 0 : EFFECT.seasons[ls.year].combos[k].meanPct;
      assert(Math.abs(c.ersPct - fx) < 1e-4, c.id + ': the driven battery effect of ers-effect.json');
      // (|| 0: a tiny negative effect rounds to -0, which js/seasons-data.js, JSON, writes as 0: v6.2 2026 Red Bull -0.0005 %)
      assert.strictEqual(d.est.ersPct, Math.round(fx * 1000) / 1000 || 0, c.id + ' est.ersPct');
      if (k !== null) assert(EFFECT.seasons[ls.year].combos[k].cars.includes(c.id), c.id + ' measured with its own battery');
    }
  }
  const row = id => LOG.seasons.find(q => q.year === +id.slice(0, 4)).cars.find(c => c.id === id);
  // no KERS costs lap time (0.4..0.7 s a lap): those cars get a stronger chassis than their pace alone would give
  for (const id of NO_KERS) assert(row(id).ersPct > 0.3 && row(id).profilePct < row(id).targetPct - 0.3, id + ' ' + JSON.stringify([row(id).ersPct, row(id).profilePct, row(id).targetPct]));
  // a strong battery is faster, a weak one slower (driven)
  assert(row('2014-mercedes').ersPct < 0 && row('2014-red-bull').ersPct > 0 && row('2015-mclaren').ersPct > row('2015-red-bull').ersPct);
  assert(row('2026-aston-martin').ersPct > 0 && row('2026-mercedes').ersPct < 0);
  // the character: Mercedes 2014's chassis alone is slower than its lap (the battery makes up), McLaren-Honda 2015's faster
  assert(row('2014-mercedes').profilePct > row('2014-mercedes').targetPct && row('2015-mclaren').profilePct < row('2015-mclaren').targetPct);
});

test('2026: the order of js/cars-data.js is kept with the new batteries (lap with the battery deployed)', () => {
  const s = SEASONS.find(q => q.year === 2026);
  const ours = s.cars.slice(1).slice().sort((a, b) => a.est.lapPct - b.est.lapPct).map(c => c.id.slice(5));
  const theirs = CARS26.filter(c => c.id !== 'standard').sort((a, b) => a.est.lapPct - b.est.lapPct).map(c => c.id);
  assert.deepStrictEqual(ours, theirs);
  // Aston Martin's weak battery (0.88 / 0.88) costs lap time, so its chassis level is raised; Mercedes' lowered
  const lvl = id => LOG.seasons.find(q => q.year === 2026).cars.find(c => c.id === id).levelPct;
  assert(lvl('2026-aston-martin') > 0 && lvl('2026-mercedes') < 0, 'levels ' + lvl('2026-aston-martin') + ' / ' + lvl('2026-mercedes'));
});

// determinism: the driven battery effect is re-measured (the same deterministic drive as ers-effect.mjs) on two circuits
test('ers-effect.json is reproducible: the 2014 Mercedes battery and 2011 no-KERS re-driven on Monza and the Hungaroring', () => {
  for (const [y, k] of [[2014, '1.08/1.12/1'], [2011, 'none']]) {
    const r = spawnSync(process.execPath, [path.join(ROOT, 'devtests', 'seasons-calib', 'ers-effect.mjs'), '--probe', String(y), k, 'it-1922,hu-1986'], { cwd: ROOT, encoding: 'utf8', timeout: 120000 });
    assert.strictEqual(r.status, 0, (r.stdout || '') + (r.stderr || ''));
    const got = JSON.parse(r.stdout), want = EFFECT.seasons[y];
    for (const t of ['it-1922', 'hu-1986']) {
      assert.strictEqual(got.stdLaps[t], want.stdLaps[t], y + ' standard lap ' + t);
      assert.strictEqual(got.perTrackPct[t], want.combos[k].perTrackPct[t], y + ' ' + k + ' ' + t);
    }
  }
});

test('names shown are the fact-checked ones: livery teamZh / note / colours for 2010-2025, one Chinese name per lineage', () => {
  for (const s of SEASONS) {
    for (const c of s.cars.slice(1)) {
      const l = LIVERIES[c.id];
      assert(l, 'livery for ' + c.id);
      assert.strictEqual(c.teamZh, l.teamZh || c.team, c.id + ' teamZh');
      if (s.year < 2026) {
        assert.strictEqual(c.note, l.note || '', c.id + ' note');
        assert.strictEqual(c.colour, l.colour, c.id + ' colour');
        assert.strictEqual(c.colour2, l.colour2, c.id + ' colour2');
      }
    }
  }
  // Toro Rosso -> AlphaTauri -> RB -> Racing Bulls: 紅牛二隊 in every year (js/cars-data.js says 小紅牛 for 2026)
  const tr = SEASONS.flatMap(s => s.cars.filter(c => c.lineage === 'toro-rosso'));
  assert.strictEqual(tr.length, 17);
  for (const c of tr) assert.strictEqual(c.teamZh, '紅牛二隊', c.id);
  assert.strictEqual(F1.cars.get('2026-racing-bulls').teamZh, '紅牛二隊');
});

test('documented display overrides are applied', () => {
  assert.strictEqual(F1.cars.get('2010-sauber').team, 'BMW Sauber');
  assert.strictEqual(F1.cars.get('2011-lotus-racing').team, 'Lotus');
  assert.strictEqual(F1.cars.get('2010-lotus-racing').team, 'Lotus Racing');
  assert.strictEqual(F1.cars.get('2016-manor').team, 'Manor');
  assert.strictEqual(F1.cars.get('2019-racing-point').engine, 'BWT Mercedes M10 EQ Power+');
  assert.strictEqual(F1.cars.get('2020-racing-point').engine, 'BWT Mercedes M11 EQ Performance');
  assert.strictEqual(F1.cars.get('2014-mercedes').car, 'F1 W05 Hybrid');
  assert.strictEqual(F1.cars.get('2017-mercedes').car, 'F1 W08 EQ Power+');
  assert.strictEqual(F1.cars.get('2015-lotus-f1').car, 'E23 Hybrid');
  assert.strictEqual(F1.cars.get('2025-mercedes').car, 'F1 W16 E Performance');
  assert.strictEqual(F1.cars.get('2026-mercedes').car, 'F1 W17 E Performance');
  assert.strictEqual(F1.cars.get('2016-red-bull').engine, 'TAG Heuer F1-2016 (Renault)');
  assert.strictEqual(F1.cars.get('2012-toro-rosso').teamZh, '紅牛二隊');
});

test('get: own entries only, hostile ids are null', () => {
  assert.strictEqual(F1.cars.get('2014-mercedes').id, '2014-mercedes');
  assert.strictEqual(F1.cars.get('2014-mercedes'), F1.cars.get('2014-mercedes'), 'cached');
  for (const bad of ['constructor', '__proto__', 'toString', 'hasOwnProperty', 'valueOf', 'prototype', '', 'x'.repeat(41),
    'MERCEDES', '2014_mercedes', 'mercedes', '2014-', null, undefined, 5, {}, ['2014-mercedes'], NaN]) {
    assert.strictEqual(F1.cars.get(bad), null, String(bad));
  }
});

test('resolve: the car itself, the same lineage in another year, else that year\'s standard car', () => {
  const r = (i, y) => F1.cars.resolve(i, y).id;
  assert.strictEqual(r('2014-mercedes', 2014), '2014-mercedes');
  assert.strictEqual(r('2014-mercedes'), '2014-mercedes', 'no year: the car itself');
  assert.strictEqual(r('2014-mercedes', 1999), '2014-mercedes', 'not a season: as no year');
  assert.strictEqual(r('2014-mercedes', 2020), '2020-mercedes');
  assert.strictEqual(r('2012-toro-rosso', 2024), '2024-rb');
  assert.strictEqual(r('2024-rb', 2012), '2012-toro-rosso');
  assert.strictEqual(r('2021-alphatauri', 2026), '2026-racing-bulls');
  assert.strictEqual(r('2010-force-india', 2020), '2020-racing-point');
  assert.strictEqual(r('2021-aston-martin', 2015), '2015-force-india');
  assert.strictEqual(r('2026-audi', 2019), '2019-alfa-romeo');
  assert.strictEqual(r('2019-alfa-romeo', 2024), '2024-kick-sauber');
  assert.strictEqual(r('2012-lotus-f1', 2021), '2021-alpine');
  assert.strictEqual(r('2021-alpine', 2011), '2011-renault');
  assert.strictEqual(r('2010-lotus-racing', 2013), '2013-caterham');
  assert.strictEqual(r('2012-marussia', 2016), '2016-manor');
  assert.strictEqual(r('2010-virgin', 2015), '2015-marussia');
  assert.strictEqual(r('2013-caterham', 2016), '2016-standard', 'did not race in 2016');
  assert.strictEqual(r('2016-haas', 2012), '2012-standard');
  assert.strictEqual(r('2026-cadillac', 2025), '2025-standard');
  assert.strictEqual(r('2011-hrt', 2013), '2013-standard');
  assert.strictEqual(r('2014-standard', 2019), '2019-standard');
  assert.strictEqual(r('2009-ferrari', 2014), '2014-ferrari', 'unknown id of a known constructor');
  assert.strictEqual(r('2009-ferrari'), '2026-ferrari');
  assert.strictEqual(r('2014-mercedes', '2021'), '2021-mercedes', '4-digit string year');
});

test('resolve: unknown and hostile ids -> the standard car (DEFAULT_YEAR without a year), never null', () => {
  const r = (i, y) => F1.cars.resolve(i, y).id;
  for (const bad of ['nope', 'constructor', '__proto__', 'toString', 'hasownproperty', '', null, undefined, 42, {}, [], 'x'.repeat(50), '2014-constructor']) {
    assert.strictEqual(r(bad, 2014), '2014-standard', String(bad));
    assert.strictEqual(r(bad), '2026-standard', String(bad));
    assert.strictEqual(r(bad, 'constructor'), '2026-standard', String(bad));
    assert.strictEqual(r(bad, {}), '2026-standard');
  }
  assert.strictEqual(r('2014-mercedes', NaN), '2014-mercedes');
  assert.strictEqual(r('2014-mercedes', Infinity), '2014-mercedes');
});

test('resolve: the ids of js/cars-data.js name the 2026 cars, and their teams in other years', () => {
  const r = (i, y) => F1.cars.resolve(i, y).id;
  for (const c of CARS26) assert.strictEqual(r(c.id), '2026-' + c.id, c.id);
  assert.strictEqual(r('standard'), '2026-standard');
  assert.strictEqual(r('standard', 2012), '2012-standard');
  assert.strictEqual(r('mercedes', 2014), '2014-mercedes');
  assert.strictEqual(r('racing-bulls', 2012), '2012-toro-rosso');
  assert.strictEqual(r('audi', 2010), '2010-sauber');
  assert.strictEqual(r('alpine', 2013), '2013-lotus-f1');
  assert.strictEqual(r('aston-martin', 2011), '2011-force-india');
  assert.strictEqual(r('cadillac', 2020), '2020-standard');
  assert.strictEqual(r('haas', 2014), '2014-standard');
  // lineage keys and older constructor ids work as bare ids too
  assert.strictEqual(r('toro-rosso'), '2026-racing-bulls');
  assert.strictEqual(r('lotus-racing', 2012), '2012-caterham');
  assert.strictEqual(r('hrt'), '2026-standard');
});

test('attribution strings for the menu', () => {
  const a = F1.cars.attribution;
  assert(/F1DB/.test(a.f1db) && /CC BY 4\.0/.test(a.f1db) && /creativecommons\.org\/licenses\/by\/4\.0/.test(a.f1db), a.f1db);
  assert(/F1DB/.test(a.f1dbShort) && /CC BY 4\.0/.test(a.f1dbShort) && /modified/.test(a.f1dbShort), a.f1dbShort);
  assert(/2026/.test(a.sources2026));
  assert(a.disclaimer.length > 5);
  assert.strictEqual(a.f1db, INFO.attribution);
  assert(Object.isFrozen(a));
});

// js/cars.js in a sandbox with other data
function sandbox(seasons, info) {
  const ctx = { F1_SEASONS: seasons, F1_SEASONS_INFO: info };
  ctx.window = ctx;
  vm.createContext(ctx);
  vm.runInContext(fs.readFileSync(path.join(ROOT, 'js', 'cars.js'), 'utf8'), ctx);
  return ctx.F1.cars;
}

test('broken data: never NaN, multipliers clamped, bad cars skipped, resolve never null', () => {
  const good = JSON.parse(JSON.stringify(SEASONS.find(q => q.year === 2014)));
  const bad = JSON.parse(JSON.stringify(good));
  bad.year = 2015;
  bad.era.power = NaN; bad.era.dragK = -1; bad.era.downforce = 'x'; bad.era.gearKmh = [100, 50]; bad.era.ers = { store: null, power: 1, harvest: Infinity };
  bad.era.cockpit = 'constructor'; delete bad.era.traction;
  bad.cars = bad.cars.map(c => Object.assign({}, c, { id: c.id.replace('2014', '2015') }));
  bad.cars[1].perf = { power: 9, drag: -3, downforce: NaN, grip: '1.2', brake: null };
  bad.cars[2].id = 'constructor';
  bad.cars[3].id = '2014-mercedes';                                   // another year's id: skipped
  bad.cars[4].colour = 'red'; bad.cars[4].ratings = { topSpeed: 500 }; bad.cars[4].team = 5;
  bad.cars.push({ id: '2015-__proto__' }, { id: '2015-toString' }, null, 7);
  const cars = sandbox([good, bad, { year: 'x' }, null, { year: 2016, era: null, cars: null }], null);
  assert.deepStrictEqual(plain(cars.seasons.map(s => s.year)), [2014, 2015, 2016]);
  assert.strictEqual(cars.DEFAULT_YEAR, 2016);
  for (const y of [2014, 2015, 2016]) {
    for (const s of cars.list(y)) {
      for (const k of PHYS) assert(isFinite(s[k]) && s[k] > 0, s.id + '.' + k + ' ' + s[k]);
      if (s.ers) for (const k of ['store', 'power', 'harvest']) assert(isFinite(s.ers[k]) && s.ers[k] > 0);
      assert(COLOUR_RE.test(s.colour) && COLOUR_RE.test(s.colour2));
      assert(RATINGS.every(k => s.ratings[k] >= 0 && s.ratings[k] <= 100));
      assert(typeof s.team === 'string' && s.team);
      assert(['modern', 'halo', 'halo18'].includes(s.cockpit));
    }
  }
  const c1 = cars.get(bad.cars[1].id), e14 = good.era;
  assert.strictEqual(c1.power / F1.REF_SPEC.power, 1.05, 'power 9 clamped to 1.05 on the fallback era value');
  assert.strictEqual(cars.get('2015-constructor'), null);
  assert.strictEqual(cars.get('constructor'), null);
  assert.strictEqual(cars.list(2016).length, 1, 'a season without cars still has its standard car');
  assert.strictEqual(cars.list(2016)[0].id, '2016-standard');
  assert.strictEqual(cars.resolve('constructor').id, '2016-standard');
  assert(Math.abs(cars.get('2014-mercedes').power - e14.power * good.cars.find(c => c.id === '2014-mercedes').perf.power) < 1e-9);
});

test('corrupted data (fuzzed): every CarSpec is exactly what js/car.js drives (F1.sanitizeSpec(spec) deep-equals spec)', () => {
  const base = SEASONS.find(q => q.year === 2014);
  let seed = 12345;
  const rnd = () => { seed = (seed * 1103515245 + 12345) % 2147483648; return seed / 2147483648; };
  const pick = a => a[Math.floor(rnd() * a.length)];
  const junk = () => pick([NaN, Infinity, -Infinity, -1, 0, 1e-9, 1e9, 'x', null, undefined, {}, [], true, 5e3, 0.02, 3, 17, 12000, 600, 25000]);
  const R = F1.REF_SPEC;
  let specs = 0;
  for (let round = 0; round < 300; round++) {
    const s = JSON.parse(JSON.stringify(base));
    const e = s.era;
    for (const k of Object.keys(e)) {
      if (rnd() < 0.25) e[k] = junk();
      else if (typeof e[k] === 'number' && rnd() < 0.3) e[k] *= pick([0.24, 0.26, 3.9, 4.1, 0.099, 9.9, 10.1]);
    }
    if (rnd() < 0.3) e.gearKmh = pick([[5, 50], [60, 700], [100, 50], [], [60], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22], 'x']);
    if (rnd() < 0.3) e.ers = pick([null, false, {}, { store: 1e12, power: 1, harvest: 1e-9 }, { store: R.ers.store * 10, power: R.ers.power * 10, harvest: R.ers.harvest * 10 }]);
    if (rnd() < 0.3 && e.ers && typeof e.ers === 'object') e.ers.taperKmh = pick([[290, 345], [345, 290], [49, 100], [50, 51], [599, 600], [598, 600.5], [290, 290.5], [10, 20], 'x', [NaN, 1], [290], [290, 345, 400], null, {}]);
    // era values at the edge of the range, times the largest multiplier
    if (rnd() < 0.2) { e.power = R.power * 4; e.traction = R.traction / 4; }
    s.cars.forEach(c => {
      if (rnd() < 0.3) c.perf = { power: junk(), drag: junk(), downforce: 1.05, grip: 0.95, brake: junk(), traction: 1.05, ersPower: pick([1.05, 1.15, junk()]), ersHarvest: junk(), ersStore: pick([1.1, 0.9, junk()]) };
      if (rnd() < 0.2) c.hasErs = pick([false, true, junk()]);
      if (rnd() < 0.1) c.ersNote = junk();
      if (rnd() < 0.2) c.cylinders = junk();
      if (rnd() < 0.2) c.aspiration = junk();
      if (rnd() < 0.2) c.ratings = { topSpeed: junk(), accel: -5, cornering: 101 };
    });
    const cars = sandbox([s], null);
    for (const spec of cars.list(2014)) {
      const p = plain(spec);
      assert.deepStrictEqual(F1.sanitizeSpec(p), p, 'round ' + round + ' ' + p.id);
      specs++;
    }
  }
  assert(specs > 3000, specs + ' specs');
  // the edge case in detail: 4 x the reference's power x 1.05 is out of js/car.js's range -> the reference's power
  const s = JSON.parse(JSON.stringify(base));
  s.era.power = R.power * 4;
  s.cars[1].perf = Object.assign({}, s.cars[1].perf, { power: 1.05 });
  const cars = sandbox([s], null);
  assert.strictEqual(cars.get(s.cars[1].id).power, R.power);
  assert.strictEqual(cars.list(2014)[0].power, R.power * 4, 'the standard car keeps the edge value');
});

test('js/cars.js battery: hasErs false -> ers null (never the standard car), multipliers clamped to their ranges, the product kept in js/car.js\'s window', () => {
  const R = F1.REF_SPEC.ers;
  const s = JSON.parse(JSON.stringify(SEASONS.find(q => q.year === 2014)));
  s.cars[0].hasErs = false;                                                // the standard car: ignored
  s.cars[1].hasErs = false; s.cars[1].ersNote = '沒有電池';
  s.cars[2].perf = Object.assign({}, s.cars[2].perf, { ersPower: 1.3, ersHarvest: 0.5, ersStore: 2 });
  s.cars[3].perf = Object.assign({}, s.cars[3].perf, { ersPower: 'x', ersHarvest: NaN, ersStore: null });
  s.cars[4].hasErs = 'no';                                                 // only false removes the battery
  s.cars[5].ersNote = 'x'.repeat(300);
  const cars = sandbox([s], null), e = s.era.ers;
  assert.deepStrictEqual(plain(cars.list(2014)[0].ers), plain(e), 'the standard car keeps the era battery');
  assert.strictEqual(cars.get(s.cars[1].id).ers, null);
  assert.strictEqual(cars.get(s.cars[1].id).ratings.ers, 0, 'no battery: bar 0');
  assert.deepStrictEqual(F1.sanitizeSpec(plain(cars.get(s.cars[1].id))), plain(cars.get(s.cars[1].id)), 'js/car.js keeps ers null');
  assert.strictEqual(cars.ersNote(s.cars[1].id), '沒有電池');
  const c2 = cars.get(s.cars[2].id).ers;
  assert.deepStrictEqual([c2.power, c2.harvest, c2.store], [e.power * 1.15, e.harvest * 0.75, e.store * 1.1], 'clamped to 0.75..1.15 / 0.9..1.1');
  const c3 = cars.get(s.cars[3].id).ers;
  assert.deepStrictEqual([c3.power, c3.harvest, c3.store], [e.power, e.harvest, e.store], 'junk multipliers = 1');
  assert(cars.get(s.cars[4].id).ers, 'hasErs "no" keeps the battery');
  assert.strictEqual(cars.ersNote(s.cars[5].id).length, 120);
  // an era battery at the window's edge (2026's harvest is calibrated at 10 x the reference / 1.05): x 1.15 is clamped
  // to the edge, not replaced by the reference's tenfold smaller harvest
  const t = JSON.parse(JSON.stringify(SEASONS.find(q => q.year === 2026)));
  t.cars[1].perf = Object.assign({}, t.cars[1].perf, { ersHarvest: 1.15 });
  const h = sandbox([t], null).get(t.cars[1].id).ers.harvest;
  assert.strictEqual(h, R.harvest * 10);
  assert.strictEqual(F1.sanitizeSpec({ ers: { store: R.store, power: R.power, harvest: h } }).ers.harvest, h);
});

test('ers.taperKmh: a valid era taper reaches every car of the season (frozen), a broken one none, and car.js keeps it', () => {
  const base = JSON.parse(JSON.stringify(SEASONS.find(q => q.year === 2014)));
  const with_ = t => { const s = JSON.parse(JSON.stringify(base)); s.era.ers.taperKmh = t; return sandbox([s], null).list(2014); };
  for (const spec of with_([300, 340])) {
    assert.deepStrictEqual(plain(spec.ers.taperKmh), [300, 340], spec.id);
    assert(Object.isFrozen(spec.ers.taperKmh), spec.id + ' frozen');
    assert.deepStrictEqual(F1.sanitizeSpec(plain(spec)), plain(spec), spec.id + ': js/car.js keeps the taper');
  }
  for (const bad of [[340, 300], [40, 100], [300, 300.5], [300, 601], [300], 'x', null, { 0: 300, 1: 340 }]) {
    for (const spec of with_(bad)) assert(!('taperKmh' in spec.ers), JSON.stringify(bad) + ' ' + spec.id);
  }
  for (const spec of F1.cars.list(2014)) assert(!('taperKmh' in spec.ers), spec.id + ': no taper before 2026');
});

// ---- the drivers of every car: the names of the computer drivers (cars[].drivers, F1.cars.drivers) ------------------
const STD_DRIVERS = [{ name: 'Alex Rowan', abbr: 'ROW', number: 90 }, { name: 'Sam Ellery', abbr: 'ELL', number: 91 }];
test('drivers: every car has two drivers of its F1DB entry (most starts first), unique in its season; the standard car two invented ones', () => {
  const real = { name: new Set(), abbr: new Set(), number: new Set() };
  for (const r of RAW.seasons) for (const e of r.entries) for (const d of e.drivers) { real.name.add(d.name); real.abbr.add(d.abbreviation); real.number.add(+d.number); }
  let n = 0;
  for (const s of SEASONS) {
    const raw = RAW.seasons.find(r => r.year === s.year), names = new Set(), abbrs = new Set();
    for (const c of s.cars) {
      assert(Array.isArray(c.drivers) && c.drivers.length === 2, c.id + ' has two drivers');
      assert.deepStrictEqual(F1.cars.drivers(c.id), c.drivers, c.id + ': F1.cars.drivers = the data');
      for (const d of c.drivers) {
        assert.deepStrictEqual(Object.keys(d), ['name', 'abbr', 'number'], c.id);
        assert(typeof d.name === 'string' && d.name.length >= 3 && Array.from(d.name).length <= 40 && d.name === d.name.trim() && !/\s\s/.test(d.name), c.id + ' name ' + d.name);
        assert(/^[A-Z]{3}$/.test(d.abbr), c.id + ' abbr ' + d.abbr);
        assert(Number.isInteger(d.number) && d.number >= 0 && d.number <= 99, c.id + ' number ' + d.number);
        assert(!names.has(d.name) && !abbrs.has(d.abbr), s.year + ': ' + d.name + ' / ' + d.abbr + ' twice');
        names.add(d.name); abbrs.add(d.abbr); n++;
      }
      if (c.id === s.year + '-standard') {
        assert.deepStrictEqual(c.drivers, STD_DRIVERS, c.id);
        for (const d of c.drivers) for (const k of ['name', 'abbr', 'number']) assert(!real[k].has(d[k]), c.id + ': ' + d[k] + ' is a real driver\'s ' + k);
        continue;
      }
      const e = raw.entries.find(x => x.id === c.id);
      const src = c.drivers.map(d => e.drivers.find(x => x.name === d.name));
      src.forEach((x, i) => assert(x && x.abbreviation === c.drivers[i].abbr && +x.number === c.drivers[i].number, c.id + ': ' + c.drivers[i].name + ' is a driver of the F1DB entry'));
      assert(src[0].starts >= src[1].starts, c.id + ': the first seat has the most starts');
      // nobody of this entry with more starts is left out, except a driver who started at least as often for another car
      for (const x of e.drivers) if (!src.includes(x) && x.starts > src[1].starts) {
        assert(raw.entries.some(o => o !== e && o.drivers.some(y => y.id === x.id && y.starts >= x.starts)), c.id + ': ' + x.name + ' (' + x.starts + ' starts) left out');
      }
    }
  }
  assert.strictEqual(n, 2 * (17 + 180));
});

test('drivers: known line-ups (2026 Ferrari, 2025 Red Bull / Racing Bulls after the swap, 2014 Mercedes, 2016 Red Bull / Toro Rosso)', () => {
  const names = id => F1.cars.drivers(id).map(d => d.name);
  assert.deepStrictEqual(names('2026-ferrari').sort(), ['Charles Leclerc', 'Lewis Hamilton']);
  assert.deepStrictEqual(names('2025-red-bull'), ['Max Verstappen', 'Yuki Tsunoda']);     // Tsunoda 22 starts here, 2 at Racing Bulls
  assert.deepStrictEqual(names('2025-racing-bulls'), ['Isack Hadjar', 'Liam Lawson']);   // Lawson 22 here, 2 at Red Bull
  assert.deepStrictEqual(F1.cars.drivers('2014-mercedes'), [{ name: 'Lewis Hamilton', abbr: 'HAM', number: 44 }, { name: 'Nico Rosberg', abbr: 'ROS', number: 6 }]);
  assert.deepStrictEqual(names('2016-red-bull'), ['Daniel Ricciardo', 'Max Verstappen']); // Kvyat's 3 starts: not named
  assert.deepStrictEqual(names('2016-toro-rosso'), ['Carlos Sainz Jr.', 'Daniil Kvyat']);
  assert.deepStrictEqual(names('2010-sauber'), ['Kamui Kobayashi', 'Pedro de la Rosa']);  // Heidfeld 5 starts
  assert(names('2026-audi').includes('Nico H' + String.fromCharCode(0xfc) + 'lkenberg'), 'F1DB\'s Latin names, accents kept');
});

test('F1.cars.drivers: a new array of new objects on every call, own car ids only, never part of a CarSpec', () => {
  const a = F1.cars.drivers('2026-mercedes');
  a[0].name = 'x'; a.push({ name: 'y' });
  assert.deepStrictEqual(F1.cars.drivers('2026-mercedes').map(d => d.name), ['George Russell', 'Kimi Antonelli']);
  for (const bad of ['constructor', '__proto__', 'toString', 'hasOwnProperty', 'valueOf', '', null, undefined, 5, {}, [], 'mercedes', 'standard',
    '2009-ferrari', '2026-constructor', 'x'.repeat(41)]) assert.deepStrictEqual(F1.cars.drivers(bad), [], String(bad));
  for (const s of F1.cars.seasons) for (const spec of F1.cars.list(s.year)) assert(!('drivers' in spec), spec.id + ': drivers are not in the CarSpec');
});

test('broken drivers data: hidden characters removed, names clamped, abbreviations / numbers repaired, at most two, the standard car invented', () => {
  const ch = String.fromCharCode, ZW = ch(0x200b), RLO = ch(0x202e), LS = ch(0x2028), BOM = ch(0xfeff), NUL = ch(0), C1 = ch(0x85);
  const buemi = 'S' + 'e' + ch(0x301) + 'bastien  Buemi' + LS;                             // decomposed e + acute: NFC
  const s = JSON.parse(JSON.stringify(SEASONS.find(q => q.year === 2014)));
  delete s.cars[0].drivers;                                                                  // the standard car: the invented two
  s.cars[1].drivers = [{ name: '  Max' + ZW + '  ' + RLO + 'Power' + NUL + C1 + ' ', abbr: 'max', number: '07' }, { name: buemi, abbr: 'BUE', number: 100 },
    { name: 'Third Driver', abbr: 'THI', number: 3 }];
  s.cars[2].drivers = [null, 7, 'x', {}, { name: '' }, { name: ZW + RLO + BOM }, { name: 'A'.repeat(60), abbr: 'AAA', number: 1.5 },
    { name: 'A'.repeat(60) + 'B', abbr: 'AAB', number: -1 }, { name: 'Ninth', abbr: 'NIN', number: 9 }];
  s.cars[3].drivers = 'Lewis Hamilton';
  s.cars[4].drivers = { 0: { name: 'x' }, length: 1 };
  s.cars[5].drivers = JSON.parse('[{"__proto__": {"name": "Polluted"}}, {"name": "Carlos Sainz Jr.", "constructor": 1, "number": "55"}]');
  s.cars[6].drivers = [{ name: 'Nico H' + ch(0xfc) + 'lkenberg', abbr: 'hul', number: '1e1' }];
  s.cars[7].drivers = [{ name: 'Al', abbr: 7 }];
  const cars = sandbox([s], null);
  assert.deepStrictEqual(plain(cars.drivers('2014-standard')), STD_DRIVERS, 'the standard car without data: the invented two');
  assert.deepStrictEqual(plain(cars.drivers(s.cars[1].id)), [{ name: 'Max Power', abbr: 'POW', number: 7 }, { name: 'S' + ch(0xe9) + 'bastien Buemi', abbr: 'BUE', number: null }]);
  assert.deepStrictEqual(plain(cars.drivers(s.cars[2].id)), [{ name: 'A'.repeat(40), abbr: 'AAA', number: null }], 'clamped to 40; the same clamped name once; 8 entries looked at');
  assert.deepStrictEqual(plain(cars.drivers(s.cars[3].id)), []);
  assert.deepStrictEqual(plain(cars.drivers(s.cars[4].id)), []);
  assert.deepStrictEqual(plain(cars.drivers(s.cars[5].id)), [{ name: 'Carlos Sainz Jr.', abbr: 'SAI', number: 55 }], 'own properties only');
  assert.deepStrictEqual(plain(cars.drivers(s.cars[6].id)), [{ name: 'Nico H' + ch(0xfc) + 'lkenberg', abbr: 'HUL', number: null }]);
  assert.deepStrictEqual(plain(cars.drivers(s.cars[7].id)), [{ name: 'Al', abbr: '', number: null }]);
  for (const spec of cars.list(2014)) assert.deepStrictEqual(F1.sanitizeSpec(plain(spec)), plain(spec), spec.id + ': the CarSpec is untouched');
  // the standard car's own data wins; no data at all: nothing
  const t = JSON.parse(JSON.stringify(SEASONS.find(q => q.year === 2014)));
  t.cars[0].drivers = [{ name: 'Test One', abbr: 'TON', number: 1 }];
  assert.deepStrictEqual(plain(sandbox([t], null).drivers('2014-standard')), [{ name: 'Test One', abbr: 'TON', number: 1 }]);
  assert.deepStrictEqual(plain(sandbox(undefined, undefined).drivers('2025-standard')), []);
});

test('F1.AI.lineup with F1.cars.drivers: 15 computer drivers of every season all named after real drivers of their car, unique, <= 16 characters', () => {
  require(path.join(ROOT, 'js', 'ai.js'));
  const AI = F1.AI;
  for (const s of F1.cars.seasons) {
    const cars = F1.cars.list(s.year), human = cars[1].id;
    const field = AI.lineup({ cars, taken: [human], count: 15, skill: 'pro', seed: 1, drivers: F1.cars.drivers, names: ['Player'] });
    assert.strictEqual(field.length, 15, s.year);
    assert.strictEqual(new Set(field.map(b => b.name)).size, 15, s.year + ': unique names');
    for (const b of field) {
      const d = F1.cars.drivers(b.car).find(x => AI.shortName(x.name) === b.name);
      assert(d, s.year + ': ' + b.name + ' drives ' + b.car + ' (no invented name)');
      assert(Array.from(b.name).length <= 16 && b.abbr === d.abbr, b.name);
    }
    // the human's team: the teammate (second seat) drives the other car
    const mate = F1.cars.drivers(human)[1].name;
    assert(field.some(b => b.car === human && b.name === AI.shortName(mate)), s.year + ': ' + mate + ' is the human\'s teammate');
  }
});

// The era pace index, checked independently of the builder's calibration code: every season's standard car on the
// racing line built for it (js/raceline.js's speed profile = what the autopilot of devtests/seasons-calib/check-drive.js
// drives within ~0.02 %), on four circuits, against the 2025 standard car. The builder solves the index as the median
// over all 40 circuits; any four must stay within 0.6 % (single circuits scatter by 1..2 % in the low-downforce years).
// When devtests/seasons-calib/calibration.json says `deploy` (the index matched with the battery in use, as on a real
// pole lap: review finding S1) the racing line's profile, which has no battery, cannot show it: both cars are then
// DRIVEN deploying (a keyboard racing-line autopilot holding E on full throttle above 100 km/h, flying lap = the
// better of laps 2 and 3, the battery refilled only by harvesting).
const CALIB = JSON.parse(fs.readFileSync(path.join(ROOT, 'devtests', 'seasons-calib', 'calibration.json'), 'utf8'));
function deployLap(track, spec) {
  const car = F1.createCar(spec, { tyres: false }), line = F1.buildRaceLine(track, car.perf);
  const S = track.samples, N = S.length, ds = track.length / N, P = line.points, st = car.state, dt = 1 / 120;
  const input = { up: false, down: false, left: false, right: false, boost: false }, laps = [];
  let time = 0, lapStart = 0, prev = 0;
  car.reset(track, 0);
  while (laps.length < 3 && time < 900) {
    line.update(st);
    const v = Math.max(0, st.speed), lv = line.levels[2];
    input.up = lv < 0.45 || v < 5; input.down = lv >= 0.6 && v >= 5;
    input.boost = input.up && !input.down && v > 100 / 3.6;
    const tp = P[(st.sampleIndex + Math.round(Math.min(35, Math.max(7, 5 + 0.3 * v)) / ds)) % N];
    const dx = tp.x - st.x, dz = tp.z - st.z;
    const kap = 2 * (dx * Math.cos(st.heading) - dz * Math.sin(st.heading)) / (dx * dx + dz * dz);
    const want = Math.max(-1, Math.min(1, Math.atan(kap * 3.6) * (1 + (v / 22) * (v / 22)) / 0.35));
    input.left = want > st.steer + 0.03; input.right = want < st.steer - 0.03;
    car.update(dt, input, track);
    time += dt;
    if (prev > N * 0.75 && st.sampleIndex < N * 0.25) {
      const s0 = S[0], tc = time - Math.max(0, Math.min((st.x - s0.x) * s0.tx + (st.z - s0.z) * s0.tz, 3)) / Math.max(st.speed, 1);
      laps.push(tc - lapStart); lapStart = tc;
    }
    prev = st.sampleIndex;
  }
  line.dispose();
  return Math.min(laps[1], laps[2]);
}
test('era pace index on 4 check circuits (Sepang, COTA, Jeddah, Zandvoort): median within 0.6 % every season' + (CALIB.deploy ? ' (driven, deploying)' : ''), () => {
  global.THREE = require(path.join(ROOT, 'lib', 'three.min.js'));
  require(path.join(ROOT, 'tracks-data.js'));
  require(path.join(ROOT, 'js', 'track.js'));
  require(path.join(ROOT, 'js', 'raceline.js'));
  const ids = ['my-1999', 'us-2012', 'sa-2021', 'nl-1948'];
  const tracks = ids.map(i => F1.buildTrack(global.F1_TRACKS.find(t => t.id === i)));
  const lap = CALIB.deploy ? deployLap : (t, spec) => { const l = F1.buildRaceLine(t, F1.carPerf(spec)); const x = l.lapTime; l.dispose(); return x; };
  const ref = tracks.map(t => lap(t, F1.REF_SPEC));
  const med = a => { const s = a.slice().sort((x, y) => x - y); return 0.5 * (s[1] + s[2]); };
  const errs = [];
  for (const s of SEASONS) {
    const std = F1.cars.get(s.year + '-standard');
    const r = med(tracks.map((t, i) => lap(t, std) / ref[i]));
    const err = r / s.paceIndex - 1;
    errs.push(s.year + ' ' + (err * 100).toFixed(2) + '%');
    assert(Math.abs(err) <= 0.006, s.year + ': ' + r.toFixed(4) + ' vs index ' + s.paceIndex);
  }
  tracks.forEach(t => t.dispose && t.dispose());
  console.log('       ' + errs.join(', '));
});

test('no data at all: resolve still gives a car (the reference)', () => {
  const cars = sandbox(undefined, undefined);
  assert.strictEqual(cars.seasons.length, 0);
  assert.strictEqual(cars.list(2026).length, 0);
  assert.strictEqual(cars.get('2025-standard'), null);
  const s = cars.resolve('2014-mercedes', 2014);
  assert(s && s.id === '2025-standard');
  assert.deepStrictEqual(JSON.parse(JSON.stringify(s)), JSON.parse(JSON.stringify(F1.REF_SPEC)), 'the fallback is the reference car');
  assert(/F1DB/.test(cars.attribution.f1db));
});

test('js/seasons-data.js loads as a plain script, as a node module and in a worker-like global', () => {
  const src = fs.readFileSync(path.join(ROOT, 'js', 'seasons-data.js'), 'utf8');
  const w = { }; w.window = w; vm.createContext(w); vm.runInContext(src, w);
  assert(Array.isArray(w.F1_SEASONS) && w.F1_SEASONS.length === 17 && w.F1_SEASONS_INFO);
  const g = {}; vm.createContext(g); vm.runInContext(src, g);
  assert(Array.isArray(vm.runInContext('globalThis.F1_SEASONS', g)));
  assert.strictEqual(JSON.stringify(require(path.join(ROOT, 'js', 'seasons-data.js'))), JSON.stringify(SEASONS));
});

// review finding S4: calibrate.mjs only printed a warning when it missed the index, and the doc's table was hand-copied
test('the calibration hit every era index within the task\'s 0.3 % (build-cars refuses one that does not)', () => {
  for (const s of SEASONS) {
    const c = CALIB.seasons[s.year];
    assert.strictEqual(c.index, s.paceIndex, s.year);
    assert(Math.abs(c.drivenMedian - c.index) <= 0.003, s.year + ': driven ' + c.drivenMedian + ' vs index ' + c.index);
  }
});

test('tools/build-cars.mjs --check: js/seasons-data.js and the calibration table of docs/seasons-data.md are up to date', () => {
  const r = spawnSync(process.execPath, [path.join(ROOT, 'tools', 'build-cars.mjs'), '--check', '--quiet'], { cwd: ROOT, encoding: 'utf8', timeout: 300000 });
  assert.strictEqual(r.status, 0, (r.stdout || '') + (r.stderr || ''));
  assert(/up to date\s+docs\/seasons-data\.md/.test(r.stdout), r.stdout);
  assert(/up to date\s+js\/seasons-data\.js/.test(r.stdout), r.stdout);
});

console.log(failed ? '\n' + failed + ' test(s) FAILED' : '\nall cars tests passed');
process.exit(failed ? 1 : 0);
