// node devtests/ai-test/build-drivers.mjs [--js out.js]
// The real drivers of every car of the seasons 2010..2026: the computer drivers' names (F1.AI.lineup's
// `drivers(carId)`). The game reads them from js/seasons-data.js cars[].drivers with F1.cars.drivers(carId) (folded in
// by tools/build-cars.mjs, AI integration 2026-10-01): from tools/seasons-raw.json (F1DB, CC BY 4.0), the two drivers of
// each entry with the most starts (first = the most starts; ties keep F1DB's order; a driver who drove two cars of one
// season is named for the one he started most often in), as { name, abbr, number } (number an integer); the standard
// car has two invented names. This script writes the same lists (tools/build-cars.mjs seasonDrivers, the real entries
// only) to devtests/ai-test/drivers.json for the simulations, and checks every car of js/seasons-data.js against them:
// exit code 1 when that file is stale (run node tools/build-cars.mjs). --js also writes a classic script
// (window.F1_DRIVERS = {carId: [...]}), no longer needed by the game.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';
const here = dirname(fileURLToPath(import.meta.url)), root = join(here, '..', '..');
const { seasonDrivers, STANDARD_DRIVERS } = await import(pathToFileURL(join(root, 'tools', 'build-cars.mjs')).href);
const raw = JSON.parse(readFileSync(join(root, 'tools', 'seasons-raw.json'), 'utf8'));
globalThis.window = globalThis;
const require = createRequire(import.meta.url);
require(join(root, 'js', 'seasons-data.js')); require(join(root, 'js', 'cars.js'));
const F1 = globalThis.F1;

const out = {}, problems = [];
for (const season of raw.seasons) for (const [id, list] of seasonDrivers(season, problems)) out[id] = list;
const stale = [];
let cars = 0;
for (const s of F1.cars.seasons) for (const c of F1.cars.list(s.year)) {
  cars++;
  const want = /-standard$/.test(c.id) ? STANDARD_DRIVERS : out[c.id];
  if (!want || want.length < 2) problems.push(c.id + ': without two drivers');
  if (JSON.stringify(F1.cars.drivers(c.id)) !== JSON.stringify(want || [])) stale.push(c.id);
}
writeFileSync(join(here, 'drivers.json'), JSON.stringify(out, null, 0).replace(/\],"/g, '],\n"') + '\n');
console.log(Object.keys(out).length + ' entries, ' + cars + ' cars of the game (standard cars included)');
if (problems.length) console.log('PROBLEMS:\n  ' + problems.join('\n  '));
if (stale.length) console.log('js/seasons-data.js differs (run node tools/build-cars.mjs): ' + stale.join(', '));
else console.log('F1.cars.drivers matches for every car');
if (problems.length || stale.length) process.exitCode = 1;
const i = process.argv.indexOf('--js');
if (i > 0) {
  const file = process.argv[i + 1];
  writeFileSync(file, '// GENERATED by devtests/ai-test/build-drivers.mjs from tools/seasons-raw.json (F1 data (c) F1DB, CC BY 4.0).\n' +
    '// The two drivers of every car of the seasons 2010..2026 (most starts first): names of the computer drivers.\n' +
    '// (The game uses F1.cars.drivers(carId) from js/seasons-data.js instead.)\n' +
    'window.F1_DRIVERS = ' + JSON.stringify(out) + ';\n');
  console.log('-> ' + file);
}
