// node devtests/ai-test/build-drivers.mjs [--js out.js]
// The real drivers of every car of the seasons 2010..2026 for the computer drivers' names (F1.AI.lineup's
// `drivers(carId)`): from tools/seasons-raw.json (F1DB, CC BY 4.0), the two drivers of each entry with the most starts
// (first = the most starts; ties keep F1DB's order), as { name, abbr, number }. Every car id of js/seasons-data.js is
// checked against it. Writes devtests/ai-test/drivers.json; --js also writes a classic script
// (window.F1_DRIVERS = {carId: [...]}) for the game - proposed for the integration as js/drivers-data.js, or the
// same lists folded into js/seasons-data.js by tools/build-cars.mjs (cars[].drivers).
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const here = dirname(fileURLToPath(import.meta.url)), root = join(here, '..', '..');
const raw = JSON.parse(readFileSync(join(root, 'tools', 'seasons-raw.json'), 'utf8'));
globalThis.window = globalThis;
const require = createRequire(import.meta.url);
require(join(root, 'js', 'seasons-data.js')); require(join(root, 'js', 'cars.js'));
const F1 = globalThis.F1;

const out = {};
for (const season of raw.seasons) {
  for (const e of season.entries) {
    const ds = (e.drivers || []).map((d, i) => ({ d, i })).sort((a, b) => (b.d.starts || 0) - (a.d.starts || 0) || a.i - b.i).slice(0, 2);
    out[e.id] = ds.map(({ d }) => ({ name: d.name, abbr: d.abbreviation || '', number: d.number || '' }));
  }
}
const missing = [];
let cars = 0;
for (const s of F1.cars.seasons) for (const c of F1.cars.list(s.year)) {
  if (/-standard$/.test(c.id)) continue;
  cars++;
  if (!out[c.id] || out[c.id].length < 2) missing.push(c.id);
}
writeFileSync(join(here, 'drivers.json'), JSON.stringify(out, null, 0).replace(/\],"/g, '],\n"'));
console.log(Object.keys(out).length + ' entries, ' + cars + ' cars of the game; without two drivers: ' + (missing.join(', ') || 'none'));
const i = process.argv.indexOf('--js');
if (i > 0) {
  const file = process.argv[i + 1];
  writeFileSync(file, '// GENERATED by devtests/ai-test/build-drivers.mjs from tools/seasons-raw.json (F1 data (c) F1DB, CC BY 4.0).\n' +
    '// The two drivers of every car of the seasons 2010..2026 (most starts first): names of the computer drivers.\n' +
    'window.F1_DRIVERS = ' + JSON.stringify(out) + ';\n');
  console.log('-> ' + file);
}
