// Verdicts, findings and proposed corrections per circuit (numbers from out/measure-<id>.json, written by audit.mjs;
// sim.mjs for the simulated pipeline results). Every 'real' value names its source.
const OSM = (id, extra) => `OpenStreetMap (ODbL) via the Overpass API, cached in devtests/track-audit/cache/overpass/${id}.json${extra ? '; ' + extra : ''}`;
const WAL = 'SPW "Relief de la Wallonie - Modele Numerique de Terrain (MNT) 2021-2022", 0.5 m lidar DTM, (c) SPW, https://geoservices.wallonie.be/arcgis/rest/services/RELIEF/WALLONIE_MNT_2021_2022/MapServer (identify; catalogue https://geoportail.wallonie.be/catalogue/e257f5df-6c96-4118-b4d2-1e63e955df53.html); samples cached in devtests/track-audit/cache/wallonia-mnt2021/points.json';
const AHN = 'AHN4 DTM 0.5 m (Actueel Hoogtebestand Nederland, CC0), https://ahn.arcgisonline.nl/arcgis/rest/services/AHNviewer/AHN4_DTM_50cm/ImageServer (getSamples); cached in devtests/track-audit/cache/ahn4/points.json';
const BW = 'LGL-BW DGM1 (1 m lidar DTM, 2022 survey, Datenlizenz Deutschland Namensnennung 2.0), https://opengeodata.lgl-bw.de/data/dgm/dgm1_32_{467,469}_{5462,5464}_2_bw.zip; cached in devtests/track-audit/cache/bw-dgm1-xyz/';
const RLP = 'LVermGeo RLP DGM1 (1 m lidar DTM, 2025 tiles, Datenlizenz Deutschland Namensnennung 2.0), https://geobasis-rlp.de/data/dgm1/current/tif/dgm1_32_{352..354}_{5576..5578}_1_rp_2025.tif; cached in devtests/track-audit/cache/rlp-dgm1/';
const EA = 'Environment Agency LIDAR Composite DTM 1 m (Open Government Licence), WCS https://environment.data.gov.uk/spatialdata/lidar-composite-digital-terrain-model-dtm-1m (GetCoverage GeoTIFF, EPSG:27700); cached in devtests/track-audit/cache/ea-lidar/';
const PITLIM ='planetf1.com/news/dutch-grand-prix-pit-lane-change-strategic-curveball-zandvoort (2025): Zandvoort raised from 60 to 80 km/h, "matching the speed limit at most other venues"';
const GAMEPIT = 'The game\'s pit lane (js/track.js) is generated beside the start / finish straight from up to 250 m before to 250 m after the line; it cannot follow a real lane that leaves at a chicane or rejoins after the first corner.';

export const FINDINGS = {
  // ------------------------------------------------------------------------------------------------ Spa-Francorchamps
  'be-1925': {
    verdict: 'major issues',
    summary: 'Layout, length, direction, start line and pit side are right. The height profile is badly wrong: the game uses the Copernicus GLO-90 SURFACE model (90 m pixels, trees included) smoothed over ~125 m, which flattens the Eau Rouge / Raidillon climb from 15 % to 3.9 % where it really is, moves the climb 150-900 m up the Kemmel straight (11.6-12.4 % there instead of 4.6 %), and puts a 20-30 m high forest-canopy hump between Paul Frere, Blanchimont and the Bus Stop (invented grades of +11 % / -9 % where the road climbs gently at 1-4 %). This is why the climb "cannot be felt". The Wallonia 0.5 m lidar DTM, run through the build\'s existing terrain-model pipeline, keeps Raidillon at 14.3-14.5 %. Scenery: a phantom concrete deck floats over the road on the descent to Eau Rouge.',
    findings: [
      { aspect: 'gradient', severity: 'major',
        game: 'Eau Rouge / Raidillon (OSM ways 126835639 + 126835637, 1.0-1.2 km after the game line): 3.9 % over 50 m (4.2 % over 100 m) at the real steepest point; the Raidillon way rises 14.6 m in the game. The game\'s steepest climbs are instead on the Kemmel straight: 12.4 % (50 m) at 1.93 km and 11.6-11.8 % at 1.18 km, where the real road climbs 4.6 %.',
        real: 'Lidar along the OSM centreline: max 15.0 % over 50 m (14.3 % over 100 m, 15.1 % over 10-20 m) at 1.03 km after the line (Raidillon), rising 24.1 m over the 220 m Raidillon way and 24.5 m from the Eau Rouge dip (389.6 m ASL) to the top; the Kemmel straight then climbs a steady 4.3-4.8 % (47.9 m over 1055 m). Published: fr.wikipedia "Raidillon de l\'Eau Rouge": "cote tres raide a 17 %" (citing spa-francorchamps.be), "denivele d\'environ 40 metres"; en.wikipedia photo caption: "maximum gradient in excess of 18%". (The lidar figure is along the centreline; with the measured 3.3 deg cross slope the fall line is ~16 %, the inside line steeper.)',
        proposedFix: 'Switch be-1925 to the Wallonia lidar DTM (new SOURCES entry in tools/build-tracks.mjs, see proposedCorrection.elevationSource) with the existing terrain-model settings (10 m step, 50 m median, 20 m Gauss, 18 % slope limit). Simulated on the lidar (sim.mjs, incl. js/track.js\'s ~9.8 m height smoothing): Raidillon 14.3 % over 50 m / 14.5 % over 20 m (game now 3.9 %), Kemmel 4.3-4.8 %, rise 24.4 m.',
        sources: [WAL, OSM('be-1925', 'circuit relation 284560'), 'fr.wikipedia.org/wiki/Raidillon_de_l\'Eau_Rouge (cached devtests/track-audit/cache/wikipedia/fr-Raidillon_de_l\'Eau_Rouge.wiki)', 'en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps (image caption "Eau Rouge and Raidillon in 1997, with a maximum gradient in excess of 18%")'] },
      { aspect: 'elevation', severity: 'major',
        game: 'Heights from Copernicus GLO-90 (a surface model: forest canopy, grandstands). Relative to the lidar (mean-aligned) the game is up to 29.9 m too HIGH between Paul Frere and the Bus Stop (+25 m at Blanchimont, +29 m 700 m before the line) and 13-15 m too LOW at Raidillon / Kemmel and Malmedy / Bruxelles; RMS error 9.7 m. Invented grades: +9.7 % in Courbe Paul Frere (real 3.2 %), +11.9 % / -7.0 % in Blanchimont (real +1.7..2.9 %), -8.8 % on the run to the Bus Stop (real +3.6 %, i.e. the wrong sign), -10.7 % at Malmedy (real -2.1 %). 25 stretches of >= 30 m differ from the lidar by more than 2 percentage points over 100 m. Cause, checked on the build own cached GLO-90 samples (tools/elevation-cache.json, 271 of 280 keys) against the lidar at the same points: the raw GLO-90 is 11-23 m (max 43.5 m) ABOVE the ground from Paul Frere through Blanchimont to the Bus Stop (wooded: a surface model sees the canopy), +4 m (max +18) around Eau Rouge, and 2-9 m below it on the open Kemmel - Bruxelles slopes (90 m pixels averaging the hillside); the 125 m median + 50 m Gauss then smear what is left.',
        real: 'Lidar: 366.6 m ASL at Courbe Paul Frere (Stavelot, the lowest point) to 468.8 m near Malmedy (the highest), range 102.2 m (game 99.0 m); Paul Frere -> Blanchimont -> Bus Stop is a gentle climb (-1.2..+3.8 % over 20 m, +40 m in 1.6 km); the descent Bruxelles -> Pouhon reaches -7.2 % (the game has its steepest 50 m there at -7.4..-9.5 %). Published range: en.wikipedia "102.2 m (335 ft) above the lowest part" (stated in the old-circuit paragraph; the lidar gives the same figure for the current lap).',
        proposedFix: 'Same source switch as above. Pipeline simulation on the lidar (sim.mjs): 0.08 m RMS / 0.60 m max from the lidar, range 102.0 m, every section within 0.7 pp of the lidar grades. Alternatively use the 5 m lidar profile in out/profile-be-1925.json directly as a profile override.',
        sources: [WAL, 'Copernicus GLO-90 via Open-Meteo = the game\'s current source (tools/build-tracks.mjs SOURCES.glo90)', 'en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps'] },
      { aspect: 'pit', severity: 'minor',
        game: `Pit lane on the driver's right (correct), lane from 234 m before to 220 m after the line, entry line 148 m before, exit 134 m after the line (i.e. before La Source), limit 80 km/h. ${GAMEPIT}`,
        real: 'OSM way 323851541 "Pit Lane" (719 m) leaves the track 375 m before the line, at the exit of the Bus Stop chicane, runs on the right and rejoins 398 m after the line, after La Source on the descent to Eau Rouge. No source found for a limit other than the usual 80 km/h.',
        proposedFix: 'None required (generic lane, right side). If the pit model ever supports a longer lane: entry [50.4415508, 5.9667947] (first node of OSM way 323851541, Bus Stop exit), exit [50.4456821, 5.9654089] (its last node, after La Source).',
        sources: [OSM('be-1925', 'way 323851541 "Pit Lane", relation 284560 member role pit_lane')] },
      { aspect: 'start', severity: 'cosmetic',
        game: 'Line = the dataset\'s first vertex, on the straight between the Bus Stop and La Source.',
        real: 'OSM circuit relation 284560, role "start": node 258602622 is 23 m before the game\'s line (1.5 m from the centreline). (OSM node 1404684961 raceway=start-finish lies 28 m off the current lap, 1.56 km away: not the F1 line.)',
        proposedFix: 'Optional START_AT \'be-1925\': [50.4440643, 5.9651626] (OSM node 258602622); 23 m only.',
        sources: [OSM('be-1925', 'relation 284560 node member 258602622 role start')] },
      { aspect: 'banking', severity: 'minor',
        game: 'Curvature-derived bank up to 5.9 deg: 5.1-5.6 deg through the Bus Stop chicane, 4-4.7 deg at Les Combes / Bruxelles / Campus, ~1 deg in Blanchimont.',
        real: 'Lidar cross slope (+-4 m): no corner beyond 4.3 deg; Bus Stop 0.1-1.4 deg, Les Combes 1.9-2.1, Bruxelles 2.5, Blanchimont -3.8 deg (inside-lower camber the game lacks), Raidillon 3.3, La Source 3.7. No real banked corner at Spa (none published).',
        proposedFix: 'Optional: bankOverrides from the lidar (proposedCorrection.bankOverridesFromLidar) or a general cap of the derived bank in chicanes; not needed for the "feel" complaint.',
        sources: [WAL] },
      { aspect: 'layout', severity: 'cosmetic',
        game: 'Current Grand Prix layout (2007-present, with the Bus Stop chicane of 2007), 7.004 km; centreline within 2.1 m (95 %) / 0.84 m mean of OSM, max 8.2 m at the La Source apex. Racing direction correct (100 %).',
        real: 'en.wikipedia infobox "Grand Prix Circuit (2007-present)", 7.004 km; FIA Media Kit 2025 Belgian GP: "Circuit length 7.004 km"; OSM lap 7004.3 m. All 2010-2026 seasons used this layout.',
        proposedFix: 'None.',
        sources: [OSM('be-1925', 'relation 284560'), 'FIA Media Kit 2025 Belgian Grand Prix, https://www.fia.com/sites/default/files/media_kit_-_2025_belgian_grand_prix.pdf (cached devtests/track-audit/cache/refs/)', 'en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps'] },
      { aspect: 'bridge', severity: 'major',
        game: 'js/scenery.js builds a concrete bridge deck OVER the road 686 m after the line (on the descent to Eau Rouge), underside 10.6 m above the road (scenery-data.js item kind "bridge" at 50.443965, 5.968340; screenshot devtests/track-audit/be-nl-de-gb/shots/shot-spa-phantom.png). It is a phantom.',
        real: 'That item is OSM way 1353164215 (man_made=bridge, layer 1, 97 m2): the outline of the track\'s OWN short deck over the pedestrian tunnel OSM way 1353164961 (footway, tunnel, layer -1) that passes UNDER the lap there. Nothing crosses over the lap at Spa in OSM (no highway / footway with bridge=yes over it). The lap also passes over the Eau Rouge stream (culverts 77352254 / 175175594) and service roads; the Wallonia DTM keeps the road surface over them (checked: no dip).',
        proposedFix: 'Do not build man_made=bridge outlines that carry the lap (outline contains the centreline and a tunnel / layer<0 way or a bridge=yes raceway lies inside it): drop OSM way 1353164215 from scenery-data.js (tools/build-scenery.mjs) or add that test to js/scenery.js addBridge. See proposedCorrection.sceneryBridgesToDrop.',
        sources: [OSM('be-1925', 'ways 1353164215 (man_made=bridge) and 1353164961 (footway tunnel)'), 'game: node devtests/track-audit/be-nl-de-gb/bridges.js be-1925 (js/scenery.js debug footprints, over = true)'] },
    ],
    correction: {
      elevationSource: {
        id: 'walmnt', apply: 'ELEV_SOURCE[\'be-1925\'] = \'walmnt\'',
        label: 'SPW Relief de la Wallonie MNT 2021-2022 (0.5 m lidar DTM), (c) SPW 2021-2022',
        service: 'https://geoservices.wallonie.be/arcgis/rest/services/RELIEF/WALLONIE_MNT_2021_2022/MapServer/identify',
        query: 'geometry={"x":<lon>,"y":<lat>,"spatialReference":{"wkid":4326}}&geometryType=esriGeometryPoint&sr=4326&layers=all&tolerance=0&mapExtent=<lon-0.001>,<lat-0.001>,<lon+0.001>,<lat+0.001>&imageDisplay=400,400,96&returnGeometry=false&f=json -> results[0].attributes["Stretch.Pixel Value"] (string, metres)',
        perRequest: 1, concurrency: 3, delayMs: 150, approxPoints: 700,
        settings: 'dtm: true (DTM_STEP 10 m, DTM_MEDIAN_HALF 2, DTM_GAUSS_SIGMA 20 m, MAX_SLOPE 0.18)',
        licenceNote: 'Usage under the SPW conditions for its geographic web services (catalogue page); attribution "(c) SPW". Check the reuse licence before shipping; fallback = the 5 m profile in out/profile-be-1925.json.',
        expected: { rangeM: 102.0, raidillonMax50mPct: 14.3, raidillonMax20mPct: 14.5, kemmelPct: '4.3-4.8', paulFrereToBlanchimontPct: '-1.0..+3.3', rmsVsLidarM: 0.08, note: 'sim.mjs be-1925 (pipeline + js/track.js smoothing)' },
        rejectedAlternative: 'EU-DEM 25 m (OpenTopoData eudem25m) checked at 25 m: Raidillon peak shifted 100-150 m late (13.9 % at OSM s 750 vs lidar 14.4 % at 600), RMS 4.4 m vs the lidar, -19.9 % artefact: not usable.',
      },
      published: { 'be-1925': [102.2, 'lidar range of the current lap (SPW MNT 2021-2022) = en.wikipedia "102.2 m"'] },
      startAt: { 'be-1925': [50.4440643, 5.9651626], optional: true },
      sceneryBridgesToDrop: { osmWays: [1353164215], rule: 'a man_made=bridge outline that contains the lap centreline and has a tunnel / layer<0 way crossing the lap inside it, or a bridge=yes raceway inside it, is the lap own deck: do not build it over the road (tools/build-scenery.mjs or js/scenery.js addBridge)' },
    },
    sources: [WAL, OSM('be-1925', 'relation 284560 "Circuit de Spa Francorchamps"'), 'fr.wikipedia.org/wiki/Raidillon_de_l\'Eau_Rouge', 'fr.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps', 'en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps', 'FIA Media Kit 2025 Belgian Grand Prix'],
  },

  // ------------------------------------------------------------------------------------------------ Zandvoort
  'nl-1948': {
    verdict: 'major issues',
    summary: 'Layout, length, direction and the height profile (already AHN4 lidar) are right. T14 banking matches the lidar. T3 is banked progressively in reality (about 5 deg on the inside, 9-10 deg across the middle, ~20 deg only on the outer 6 m), while the game banks the whole width at 19 deg. Tarzan, Hunserug, Rob Slotemaker and Scheivlak have real 4.5-7 deg cambers the game renders at 1-3 deg. The pit limit was 60 km/h before 2025 (game: 80 for every season). Scenery: a phantom concrete deck floats over the main straight (the OSM outline of the track own deck over a service tunnel).',
    bankSkip: [[450, 620], [3141, 3692]],
    findings: [
      { aspect: 'banking', severity: 'minor',
        game: 'bankOverrides T3 Hugenholtzbocht 19 deg from lap fraction 0.20053 to 0.23226 (854-989 m): planar 19 deg across the whole road (game mean over the corner 17.7 deg).',
        real: 'AHN4 lidar cross-sections through T3 (OSM way 1311522216, 480-600 m along the OSM lap): best-fit slope over the central +-3 / +-7 / +-10 m = 8.9-10.4 deg; the profile is concave: ~5 deg on the inside half, 18-23 deg on the outer 6 m (e.g. at OSM s 520: +0.62 m over the inner 7 m, +2.50 m over the next 6 m outward). Published: en.wikipedia "turn 3 has a 19-degree bank"; nl.wikipedia gives T3 18 / T14 19 deg; OSM way 1311522216 description "Helling 32% / 18 graden". The published figure is the steep outer part.',
        proposedFix: 'Keep 19 deg as the published peak if the cross-section stays planar (it is what makes the bowl visible), or model the progressive cross-section (inside ~5 deg rising to ~20 deg at the outer edge). Do not lower it to the centre value without a variable cross-section: the user already finds the banking not pronounced.',
        sources: [AHN, OSM('nl-1948', 'way 1311522216 "Hugenholtzbocht"'), 'en.wikipedia.org/wiki/Circuit_Zandvoort', 'nl.wikipedia.org/wiki/Circuit_Zandvoort'] },
      { aspect: 'banking', severity: 'cosmetic',
        game: 'T14 Arie Luyendijkbocht 18 deg (game max 18, mean 10.3 over 551 m incl. the ramps).',
        real: 'AHN4 cross-sections OSM s 3350-3600: 11.9-17.3 deg over +-3 m, 14.6 deg over +-10 m (more uniform than T3); en.wikipedia 18 deg (nl.wikipedia 19).',
        proposedFix: 'None.',
        sources: [AHN, 'en.wikipedia.org/wiki/Circuit_Zandvoort'] },
      { aspect: 'banking', severity: 'minor',
        game: 'Curvature-derived bank: Tarzanbocht mean 3.3 deg (max 5.1), Hunserug 0.9, Rob Slotemakerbocht 1.5, Scheivlak 2.4, the braking zone before Tarzan 0.4; but 4.4-5 deg in CM.com bocht and the Hans Ernst chicane entry where the road is nearly flat.',
        real: 'AHN4 cross slopes (planar, consistent over +-3..+-10 m): Tarzanbocht 6.4-7.4 deg, the approach to Tarzan 5.1-5.4, Hunserug 4.7-5.4, Rob Slotemakerbocht 4.4-4.8 (both directions of the S), Scheivlak 4.1-5.9; CM.com bocht 1.5-1.7, Hans Ernst chicane entry 1.1-1.2. Every one inside-lower.',
        proposedFix: 'bankOverrides from the lidar (proposedCorrection.bankOverridesFromLidar: Tarzan 6.5, Hunserug 4.5, Rob Slotemaker 4.5 / 5, Scheivlak 5 deg ...). This also helps the "banking not felt" complaint at Zandvoort.',
        sources: [AHN] },
      { aspect: 'pit', severity: 'minor',
        game: 'pitLimitKmh absent -> 80 km/h for every season (js/track.js lane at 80). Lane on the right (correct), entry 169 m before the line, exit 164 m after.',
        real: '60 km/h until 2024, 80 km/h from the 2025 Dutch GP (en.wikipedia "2025 Dutch Grand Prix": "The pit lane speed limit was increased from 60 km/h to 80 km/h", citing Pirelli; speedcafe.com; planetf1.com). Whether all of 2021-2024 ran at 60 was not checked year by year (the 2025 sources call 60 the previous limit). OSM way 38144527 "Pitstraat" (759 m) leaves 173 m before the line (game 169: matches) and rejoins 615 m after it, past Tarzan.',
        proposedFix: 'Season-dependent limit: 60 km/h for the 2021-2024 Dutch GP seasons, 80 from 2025 (e.g. pitLimitKmhBySeason {"2021":60,"2022":60,"2023":60,"2024":60}); if only one value is possible keep 80 (2025-2026 and the default season 2026).',
        sources: ['en.wikipedia.org/wiki/2025_Dutch_Grand_Prix (cached)', 'speedcafe.com/f1-news-2025-dutch-grand-prix-pit-speed-limit-change-explained-fia-pirelli-strategy-shakeup/', PITLIM, OSM('nl-1948', 'way 38144527 "Pitstraat"')] },
      { aspect: 'start', severity: 'cosmetic',
        game: 'Line = dataset first vertex.',
        real: 'OSM circuit relation 13545573: node 12148116710 "Finish" (raceway=finish) 70 m after the game\'s line, node 12148116709 "Start" (raceway=start) 126 m after it.',
        proposedFix: 'Optional START_AT \'nl-1948\': [52.3889948, 4.5408762] (OSM node 12148116710, the finish = timing line).',
        sources: [OSM('nl-1948', 'relation 13545573 nodes 12148116709 / 12148116710')] },
      { aspect: 'elevation', severity: 'cosmetic',
        game: 'AHN4 lidar already (since 2026-10-01): range 8.5 m, max grade 6.2 % / -4.8 % over 50 m.',
        real: 'AHN4 along the OSM centreline: range 8.7 m (published 8.9 m, nl/en.wikipedia), max 7.6 % (Hugenholtz exit) / -5.4 % (Hunserug) over 50 m; RMS difference 0.17 m, no stretch > 2 pp over 100 m.',
        proposedFix: 'None.',
        sources: [AHN, 'nl.wikipedia.org/wiki/Circuit_Zandvoort: "Het hoogteverschil is 8,9 meter"'] },
      { aspect: 'layout', severity: 'cosmetic',
        game: 'Current layout (2020-present, banked T3 / T14), 4.259 km; within 3.0 m of OSM everywhere (mean 0.88 m); direction correct.',
        real: 'en.wikipedia infobox "Grand Prix Circuit (2020-present)" 4.259 km; OSM lap 4261.9 m. F1 used it 2021-2026.',
        proposedFix: 'None.',
        sources: [OSM('nl-1948', 'relation 13545573 "Grand Prix Formule 1 van Nederland"'), 'en.wikipedia.org/wiki/Circuit_Zandvoort'] },
      { aspect: 'bridge', severity: 'major',
        game: 'js/scenery.js builds a floating concrete deck OVER the main straight 160 m before the line (lap s 4101, underside 8.8 m above the road; scenery-data.js "bridge" at 52.387092, 4.539550; screenshot shots/shot-zandvoort-phantom.png). It is a phantom.',
        real: 'That item is OSM way 765476850 (man_made=bridge, layer 1, 232 m2) = the track\'s own deck over the service tunnel OSM way 186321842 (layer -1) under the main straight. OSM has nothing crossing over the lap; only service / foot tunnels pass under it (ways 186321842, 906789803, 906789798). AHN4 shows no dip there.',
        proposedFix: 'Drop OSM way 765476850 from the scenery bridges (proposedCorrection.sceneryBridgesToDrop) or skip man_made=bridge outlines that carry the lap.',
        sources: [OSM('nl-1948', 'ways 765476850, 186321842'), 'game: node devtests/track-audit/be-nl-de-gb/bridges.js nl-1948'] },
    ],
    correction: {
      pitLimitKmhBySeason: { 2021: 60, 2022: 60, 2023: 60, 2024: 60, 2025: 80, 2026: 80, note: '2021-2023 inferred from the 2025 sources ("raised from 60"), not checked per year' },
      startAt: { 'nl-1948': [52.3889948, 4.5408762], optional: true },
      bankOverridesKeep: 'T3 19 deg and T14 18 deg stay (published); T3 measured profile: inside ~5, centre 9-10, outer 18-23 deg',
      sceneryBridgesToDrop: { osmWays: [765476850], rule: 'a man_made=bridge outline that contains the lap centreline and has a tunnel / layer<0 way crossing the lap inside it, or a bridge=yes raceway inside it, is the lap own deck: do not build it over the road (tools/build-scenery.mjs or js/scenery.js addBridge)' },
    },
    sources: [AHN, OSM('nl-1948', 'relation 13545573'), 'en.wikipedia.org/wiki/Circuit_Zandvoort', 'nl.wikipedia.org/wiki/Circuit_Zandvoort', 'en.wikipedia.org/wiki/2025_Dutch_Grand_Prix', PITLIM],
  },

  // ------------------------------------------------------------------------------------------------ Hockenheim
  'de-1932': {
    verdict: 'major issues',
    summary: 'Layout, length, direction and start line are right. The circuit is almost flat (lidar range 4.2 m, max 1.8 % over 50 m) but the game\'s GLO-90 surface model doubles the range (7.9 m) and invents a 5 m hump on the Parabolika (forest canopy: +2.9 % / -3.7 %) and +-2.5 % around the Sachs-Kurve. The derived banking gives 4-6 deg in the hairpin and in Nord / Sued-Kurve that are 1-1.6 deg in reality. Scenery: three phantom concrete decks float over the road (OSM outlines of the track own decks over service tunnels).',
    findings: [
      { aspect: 'elevation', severity: 'minor',
        game: 'GLO-90 (surface model) heights: range 7.9 m; a hump on the Parabolika (1.3-1.6 km after the line) up to 5.3 m above the lidar with +2.9 % / -3.7 % over 100 m; -2.5 % / +2.4 % around the Sachs-Kurve; -2 % 620 m after the line; max 3.1 % / -4.1 % over 50 m. RMS error 1.72 m.',
        real: 'LGL-BW DGM1 lidar: 100.3 m ASL (Sachs-Kurve) to 104.5 m (Bernie-Ecclestone-Kurve), range 4.2 m; the Parabolika is flat (101.4 m +-0.05 over 800 m); max 1.8 % / -2.4 % over 50 m.',
        proposedFix: 'ELEV_SOURCE \'de-1932\' = a new LGL-BW DGM1 source (4 open-data XYZ zips, 2 km tiles, see proposedCorrection.elevationSource) with the terrain-model settings; or FLAT_TRACKS-style treatment. Profile in out/profile-de-1932.json.',
        sources: [BW, OSM('de-1932', 'relation 284588')] },
      { aspect: 'banking', severity: 'minor',
        game: 'Curvature-derived bank: Spitzkehre (hairpin) 5.2-6.0 deg, Nordkurve 4.2-5.0, Bernie-Ecclestone-Kurve 4.8-5.7, Suedkurve 3.8-5.1, Mobil 1 Kurve 3.5-3.8.',
        real: 'Lidar cross slope: Spitzkehre 1.4-1.5 deg, Nordkurve 0.9-1.0, Bernie-Ecclestone 2.3-2.4, Suedkurve 1.5-1.6, Mobil 1 1.2-1.7; only the Sachs-Kurve (Motodrom) has a real 4.9-5.8 deg camber (game 4.3-5.2: fine). de.wikipedia: the banked "Ostkurve" (8 % Ueberhoehung) belonged to the pre-2002 long circuit, gone.',
        proposedFix: 'bankOverrides from the lidar to flatten the hairpin / Nordkurve / Suedkurve (proposedCorrection.bankOverridesFromLidar), or cap the derived bank for tight corners.',
        sources: [BW, 'de.wikipedia.org/wiki/Hockenheimring ("Die neugeschaffene Ostkurve hatte 8 % Ueberhoehung")'] },
      { aspect: 'pit', severity: 'minor',
        game: `Right side (correct); entry 114 m before the line, exit 164 m after; 80 km/h. ${GAMEPIT}`,
        real: 'OSM way 15446020 "Boxengasse" (865 m, relation role pitlane): leaves 380 m before the line (inside of the Suedkurve) and rejoins 532 m after it (after the Nordkurve). No source found for a limit other than 80 km/h.',
        proposedFix: 'None required.',
        sources: [OSM('de-1932', 'way 15446020')] },
      { aspect: 'layout', severity: 'cosmetic',
        game: 'Grand Prix circuit 2002-present, 4.574 km; within 4.2 m of OSM (mean 1.25 m); direction correct; line 1 m from OSM node 395005281 "Start-Ziel".',
        real: 'en.wikipedia infobox "Grand Prix Circuit (2002-present)" 4.574 km (F1 2010, 2012, 2014, 2016, 2018, 2019); OSM lap 4573.3 m.',
        proposedFix: 'None.',
        sources: [OSM('de-1932', 'relation 284588, node 395005281'), 'en.wikipedia.org/wiki/Hockenheimring'] },
      { aspect: 'bridge', severity: 'major',
        game: 'js/scenery.js builds THREE floating concrete decks over the road: 554 m after the line (after the Nordkurve, underside 8.0 m above the road; screenshot shots/shot-hockenheim-phantom1.png), and in the Motodrom 3240 m and 3384 m after the line (8.5 / 8.2 m; shots/shot-hockenheim-phantom2.png).',
        real: 'They are OSM ways 1302356195, 1302600378 and 1302600377 (man_made=bridge, layer 1): the lap\'s own decks over the service / foot tunnels 31320990, 192994934, 26336602 and 534265659 (layer -2) that pass UNDER the lap. Nothing crosses over the lap in OSM. The DTM shows no dip there.',
        proposedFix: 'Drop OSM ways 1302356195, 1302600377, 1302600378 from the scenery bridges (proposedCorrection.sceneryBridgesToDrop) or skip man_made=bridge outlines that carry the lap.',
        sources: [OSM('de-1932', 'ways 1302356195 / 1302600377 / 1302600378 and the tunnels'), 'game: node devtests/track-audit/be-nl-de-gb/bridges.js de-1932'] },
    ],
    correction: {
      elevationSource: {
        id: 'bwdgm1', apply: 'ELEV_SOURCE[\'de-1932\'] = \'bwdgm1\'',
        label: 'LGL-BW DGM1 1 m lidar DTM (2022), Datenlizenz Deutschland Namensnennung 2.0, "LGL-BW (2026)"',
        files: ['https://opengeodata.lgl-bw.de/data/dgm/dgm1_32_467_5462_2_bw.zip', 'https://opengeodata.lgl-bw.de/data/dgm/dgm1_32_467_5464_2_bw.zip', 'https://opengeodata.lgl-bw.de/data/dgm/dgm1_32_469_5462_2_bw.zip', 'https://opengeodata.lgl-bw.de/data/dgm/dgm1_32_469_5464_2_bw.zip'],
        format: 'ZIP with four 1 km XYZ text files each ("E N H", ETRS89 / UTM 32N, 1 m pixel centres at .50, heights in m DHHN2016); ~12 MB per zip; reader in devtests/track-audit/be-nl-de-gb/dem.mjs (bwXyz)',
        doNotUse: 'the INSPIRE WCS owsproxy.lgl-bw.de/.../WCS_INSP_BW_Hoehe_Coverage_DGM1 returns 16-bit integers (1 m quantisation)',
        settings: 'dtm: true', expected: { rangeM: 4.1, maxGrade50mPct: 1.6, minGrade50mPct: -2.2, rmsVsLidarM: 0.05, note: 'sim.mjs de-1932 (pipeline + js/track.js smoothing)' },
      },
      sceneryBridgesToDrop: { osmWays: [1302356195, 1302600377, 1302600378], rule: 'a man_made=bridge outline that contains the lap centreline and has a tunnel / layer<0 way crossing the lap inside it, or a bridge=yes raceway inside it, is the lap own deck: do not build it over the road (tools/build-scenery.mjs or js/scenery.js addBridge)' },
    },
    sources: [BW, OSM('de-1932', 'relation 284588'), 'en.wikipedia.org/wiki/Hockenheimring', 'de.wikipedia.org/wiki/Hockenheimring'],
  },

  // ------------------------------------------------------------------------------------------------ Nurburgring GP
  'de-1927': {
    verdict: 'major issues',
    summary: 'Layout (GP-Strecke 2002-present with the Mercedes Arena and the tight NGK/Veedol car chicane), length, direction, start line and the total range (53.4 m vs lidar 55.9 m, published 55 m) are right. The GLO-90 profile misplaces gradients by 100-200 m: the 7 % climb up to the NGK chicane is 3 % in the game while the chicane itself climbs 8.5 % (real 4 %), and the Mercedes Arena gets an invented 9 m dip (-7.4 % / +5.2 % where the road is within +-2.6 %). Scenery: besides the real BMW-Bruecke, a phantom deck floats over the road 1.47 km after the line (the OSM outline of the bridge the lap itself runs on).',
    bankSkip: [],
    findings: [
      { aspect: 'gradient', severity: 'minor',
        game: 'GLO-90 profile (range 53.4 m): max +9.0 % / -9.3 % over 50 m; the climb up to the NGK chicane is displaced ~150 m: 2.6-3.1 % where the road climbs 7.1-7.4 % (670-730 m before the line) and 8.5 % (100 m) inside the chicane (550 m before the line) where it climbs 4.0 %; after T1, in the Mercedes-Arena section (0.74-1.15 km after the line), -7.4 % then +5.2 % and up to 8.8 m below the lidar; 13 stretches differ by > 2 pp over 100 m; RMS 3.4 m.',
        real: 'RLP DGM1 lidar along the OSM centreline (underpasses bridged): 564.2 m ASL (Goodyear/Dunlop-Kehre, the lowest point) to 620.1 m (~200 m before the line, Coca-Cola-Kurve / start straight), range 55.9 m (published 55 m, de.wikipedia infobox "Hoehenunterschied 55 m" for the GP-Strecke); steepest climb 8.5 % (50 m) / 8.3 % (100 m) in the Michael-Schumacher-S (game 7.2: fine), 7.1-7.4 % after the Advan-Bogen; steepest descents -6.3 % (50 m) 1.4 km before the line and -5.9 % into the Ford-Kurve; Mercedes Arena within -2.6..-1.1 %.',
        proposedFix: 'ELEV_SOURCE \'de-1927\' = a new RLP DGM1 source (9 open GeoTIFF tiles, 1 km, see proposedCorrection.elevationSource) with the terrain-model settings AND three COVERED entries (the bare-earth DTM drops 7-8 m under the lap\'s two bridges and over the service tunnel).',
        sources: [RLP, OSM('de-1927', 'relation 38567 "Nuerburgring Grand Prix Strecke"'), 'de.wikipedia.org/wiki/Nürburgring (infobox Hoehenunterschied2 = 55)'] },
      { aspect: 'bridge', severity: 'major',
        game: 'js/scenery.js builds two decks over the road: the BMW-Bruecke 50 m after the line (correct, shots/shot-nurb-bmw-real.png) and a PHANTOM floating deck 1466 m after the line (underside 8.7 m above the road, shots/shot-nurb-phantom.png) from OSM way 790945811 (man_made=bridge, layer 1, 2033 m2), which is the structure the lap itself runs ON (the raceway way 1443047846 there is bridge=yes, layer 1, together with service / footway bridges 223251412, 849684573, 74171524).',
        real: 'OSM: the only structure over the lap is the BMW-Bruecke (way 34444288, bridge=covered, cable-stayed footbridge). Way 790945811 is a bridge the lap crosses on.',
        proposedFix: 'Drop OSM way 790945811 from the scenery bridges (proposedCorrection.sceneryBridgesToDrop); keep 34444288.',
        sources: [OSM('de-1927', 'ways 790945811, 1443047846, 34444288'), 'game: node devtests/track-audit/be-nl-de-gb/bridges.js de-1927'] },
      { aspect: 'bridge', severity: 'cosmetic',
        game: 'Elevation: the lap\'s bridges are not special in the data (GLO-90 sees the embankment; fine).',
        real: 'OSM: the lap runs over two bridges (ways 1443047844 at 1.84 km before the line and 1443047846 at 1.43 km after it) and over a service tunnel (way 31010592, 0.5 km after the line); the BMW-Bruecke (way 34444288, bridge=covered) crosses over the lap. A bare-earth DTM reads the ground under the two bridges and at the tunnel (dips of 7-8 m in the raw lidar).',
        proposedFix: 'With a lidar source add COVERED for de-1927 (straight between the ends, pad 0): {name: "bridge (OSM way 1443047844)", from:[50.330283, 6.938282], to:[50.330884, 6.938575]} (OSM s 1472-1542), {name: "over service tunnel (OSM way 31010592)", from:[50.332661, 6.943229], to:[50.332344, 6.942656]} (s 3784-3838), {name: "bridge (OSM way 1443047846)", from:[50.330639, 6.939605], to:[50.330069, 6.939355]} (s 4758-4824): see proposedCorrection.covered.',
        sources: [OSM('de-1927', 'ways 1443047844, 1443047846, 31010592, 34444288'), RLP] },
      { aspect: 'layout', severity: 'cosmetic',
        game: 'GP-Strecke incl. Mercedes Arena, 5.148 km; within 2.2 m of OSM (mean 0.59 m) when the NGK chicane is taken through OSM way 1149161211; direction correct.',
        real: 'en.wikipedia infobox "GP-Strecke (2001-present)" 5.148 km (F1 2011, 2013, 2020). At the NGK (Veedol) chicane OSM has two paths: way 1149161211 (sharp left-right, the car chicane rebuilt 1997) and way 820679450 "NGK-Schikane" (a gentler line, used by OSM relation 38567; de.wikipedia: since 1997 a separate line for motorcycle races, also used in the 24 h race). The dataset follows the sharp car line (up to 30 m from way 820679450).',
        proposedFix: 'None (the dataset has the F1 line). Note for other auditors: OSM relation 38567 routes via the motorcycle variant.',
        sources: [OSM('de-1927', 'ways 1149161211 / 820679450, relation 38567'), 'de.wikipedia.org/wiki/Nürburgring ("Diese engere Streckenfuehrung ... 1997 eine gesonderte Streckenfuehrung fuer Motorradrennen")', 'en.wikipedia.org/wiki/Nürburgring'] },
      { aspect: 'banking', severity: 'minor',
        game: 'Derived bank 4.6-5.9 deg in the Mercedes Arena and NGK chicane; 3.5 deg in the Goodyear-Kehre.',
        real: 'Lidar: Mercedes Arena 1.1-1.4 deg, NGK chicane -1.0..-1.6 deg; Goodyear(Dunlop)-Kehre 5.2-5.8 deg and Ford-Kurve 4.3-4.7 deg real cambers.',
        proposedFix: 'Optional bankOverrides from the lidar (proposedCorrection.bankOverridesFromLidar).',
        sources: [RLP] },
      { aspect: 'pit', severity: 'minor',
        game: `Right side (correct); entry 130 m before the line, exit 164 m after; 80 km/h. ${GAMEPIT}`,
        real: 'OSM way 30815119 "Boxengasse" (952 m, raceway=pitlane): leaves 492 m before the line (from the NGK chicane / Coca-Cola-Kurve) and rejoins 494 m after it (after the Castrol-S / T1). de.wikipedia: "Laenge der Boxengasse: 381,4 Meter" (the garage row). No source found for a limit other than 80 km/h.',
        proposedFix: 'None required.',
        sources: [OSM('de-1927', 'way 30815119'), 'de.wikipedia.org/wiki/Nürburgring'] },
      { aspect: 'start', severity: 'cosmetic',
        game: 'Line = dataset first vertex.',
        real: 'OSM node 370477491 "Start-Ziel" is 6 m before the game line (2 m off the centreline); node 3099078401 raceway=start-finish "Nuerburgring Start-Finish" is 239 m further on (probably a grid / other series\' line).',
        proposedFix: 'None.',
        sources: [OSM('de-1927', 'nodes 370477491, 3099078401')] },
    ],
    correction: {
      elevationSource: {
        id: 'rlpdgm1', apply: 'ELEV_SOURCE[\'de-1927\'] = \'rlpdgm1\'',
        label: 'LVermGeo RLP DGM1 1 m lidar DTM, Datenlizenz Deutschland Namensnennung 2.0, "GeoBasis-DE / LVermGeoRP (2026)"',
        files: 'https://geobasis-rlp.de/data/dgm1/current/tif/dgm1_32_<E km>_<N km>_1_rp_2025.tif for E 352..354, N 5576..5578 (names from the directory listing; 1 km tiles, Float32 LZW with horizontal predictor 2 on the 32-bit words, ~1.4 MB each)',
        settings: 'dtm: true + the three COVERED entries', expected: { rangeM: 55.8, max50mPct: 8.3, min50mPct: -6.0, rmsVsLidarM: 0.08, note: 'sim.mjs de-1927 (pipeline + js/track.js smoothing, underpasses bridged)' },
      },
      covered: [{ name: 'lap bridge, OSM way 1443047844', from: [50.330283, 6.938282], to: [50.330884, 6.938575], pad: 0 }, { name: 'lap over service tunnel, OSM way 31010592', from: [50.332661, 6.943229], to: [50.332344, 6.942656], pad: 0 }, { name: 'lap bridge, OSM way 1443047846', from: [50.330639, 6.939605], to: [50.330069, 6.939355], pad: 0 }],
      sceneryBridgesToDrop: { osmWays: [790945811], keep: [34444288], rule: 'a man_made=bridge outline that contains the lap centreline and has a tunnel / layer<0 way crossing the lap inside it, or a bridge=yes raceway inside it, is the lap own deck: do not build it over the road (tools/build-scenery.mjs or js/scenery.js addBridge)' },
      published: { 'de-1927': [55, 'de.wikipedia.org/wiki/Nürburgring infobox (GP-Strecke) "Hoehenunterschied 55 m"; lidar 55.9 m'] },
    },
    sources: [RLP, OSM('de-1927', 'relation 38567'), 'de.wikipedia.org/wiki/Nürburgring', 'en.wikipedia.org/wiki/Nürburgring'],
  },

  // ------------------------------------------------------------------------------------------------ Silverstone
  'gb-1948': {
    verdict: 'major issues',
    summary: 'Layout (Arena Grand Prix circuit, 5.891 km), direction and the flat height profile (EA lidar range 11.3 m vs game 11.6 m, RMS 0.7 m) are right. But the start / finish line and the pit lane are at the OLD pits on the National Pit Straight (Woodcote -> Copse), which F1 used until 2010; since 2011 the pits and the start / finish line are at the Silverstone Wing on the Hamilton Straight (Club -> Abbey), 2.85-3.04 km further round the lap. So 16 of the 17 seasons start in the wrong place. The derived banking adds 3.5-5.7 deg in slow corners that are within 1.8 deg in reality; two real overhead structures (the Wellington Straight bridges, the Wing footbridge) are missing.',
    findings: [
      { aspect: 'start', severity: 'major',
        game: 'Line (dataset first vertex) at 52.07879, -1.01535 on the National Pit Straight between Woodcote and Copse; grid, gantry and pit lane there.',
        real: 'en.wikipedia "2011 British Grand Prix": "the pits and the start/finish line moved to the straight between Club Corner and the new Abbey" (the Silverstone Wing). OSM: node 13036050131 raceway=finish [52.0682609, -1.0234867] lies 3.04 km after the game line (2851 m before it) on the Hamilton Straight; node 13036050130 raceway=start [52.0693366, -1.0221521] 150 m further on (start and finish lines differ at Silverstone: en.wikipedia "the RAC moved the start line forward at Silverstone but not, significantly, the finish line"). The game line is right only for the 2010 season (Arena layout with the old pits).',
        proposedFix: "START_AT 'gb-1948': [52.0682609, -1.0234867] (OSM node 13036050131, the finish / timing line) - or [52.0693366, -1.0221521] (the start node) if the grid position matters more than the timing line; plus pitSide -1 (the Wing pit lane is on the right). Season 2010 would then also start at the Wing (one line per circuit).",
        sources: ['en.wikipedia.org/wiki/2011_British_Grand_Prix (cached devtests/track-audit/cache/wikipedia/en-2011_British_Grand_Prix.wiki)', 'en.wikipedia.org/wiki/Silverstone_Circuit (infobox: Arena Grand Prix Circuit 2011-present / 2010)', OSM('gb-1948', 'relation 51160 "Silverstone Grand Prix", nodes 13036050130 / 13036050131')] },
      { aspect: 'pit', severity: 'major',
        game: `Pit lane on the right of the National Pit Straight (lane 219 m before to 178 m after the line, entry 133 m before, exit 92 m after), next to the old pit building (scenery-data.js 'pit' building at 52.077865, -1.015755). ${GAMEPIT}`,
        real: 'Since 2011 the F1 pit lane is the Wing lane, OSM way 227902927 ("International pit lane", 1130 m, relation 51160 role pit_lane): on the right of the Hamilton Straight, leaving the track 607 m before the finish node (at Vale, before Club) and rejoining 706 m after it (after Abbey / Farm). The old National pit lane (OSM way 227838385, 1009 m, right side, -509..+542 m about the game line) is the 2010 one. No source found for a limit other than 80 km/h.',
        proposedFix: 'Follows from START_AT (the generated lane moves with the line); pitSide -1. tools/build-scenery.mjs should tag the Wing building (not looked up here) as kind pit so the garages are drawn there.',
        sources: [OSM('gb-1948', 'ways 227902927, 227838385')] },
      { aspect: 'banking', severity: 'minor',
        game: 'Curvature-derived bank 3.4-5.7 deg in Abbey (3.5), Village (4.8-5.6), The Loop (-4.9..-5.7), Aintree (-4.0..-4.6), Brooklands (-3.9..-4.8), Luffield (4.2-4.8), Chapel (3.5-4.1), Stowe (3.4-3.6), Vale (-5.1..-5.7), Club (3.9-5.5).',
        real: 'EA lidar cross slope: all those corners within 1.8 deg (Abbey 1.0-1.3, Village 1.6, Loop -1.7..-1.8, Aintree -0.8, Brooklands -0.3, Luffield 1.7-1.8, Chapel 0.6-0.8, Stowe 0.6, Vale +0.8 (the other side), Club -0.7..0.7). Silverstone is a flat former airfield; no banked corner published.',
        proposedFix: 'bankOverrides from the lidar (proposedCorrection.bankOverridesFromLidar) or cap the derived bank on this circuit.',
        sources: [EA] },
      { aspect: 'bridge', severity: 'minor',
        game: 'One deck over the road, on the Hangar Straight (lap s 1670, underside 8.1 m above the road) - correct.',
        real: 'OSM: three structures cross over the lap: the Hangar Straight service bridge (way 4851856 + outline 605922107: present in the game); the Wellington Straight bridges (service way 126446852, footbridges 360074746 / 360077715 at ~52.0752, -1.0154: MISSING - no man_made=bridge outline there, so the scenery build never sees them); the Wing\'s enclosed glass footbridge over the Hamilton Straight ~150 m after the finish line (way 1412628537 building=bridge, min_height 14.5 m, height 18.5 m, with the indoor footway 1412628538: MISSING). Two tunnels pass under the lap at Copse (126446849, 507989195).',
        proposedFix: 'tools/build-scenery.mjs: also emit decks for highway ways with bridge=yes and layer>0 that cross the lap, and building=bridge with min_height (the Wing footbridge, 14.5-18.5 m).',
        sources: [OSM('gb-1948', 'ways 4851856, 605922107, 126446852, 360074746, 360077715, 1412628537, 1412628538'), 'game: node devtests/track-audit/be-nl-de-gb/bridges.js gb-1948'] },
      { aspect: 'elevation', severity: 'minor',
        game: 'GLO-90 heights: range 11.6 m; the drop through Vale -1.4 % (50 m) / -1.1 % (100 m), Vale falls 3.4 m; max +2.4 % / -1.5 % over 50 m; up to 2.2 m off on the Hamilton Straight; RMS 0.68 m.',
        real: 'EA lidar: 144.9 m ASL (Hamilton Straight, by the finish line) to 156.2 m (112 m from Maggotts), range 11.3 m; the dip into Vale -3.8 % (50 m) / -3.3 % (100 m), Vale falls 5.1 m; max +1.9 % (Stowe) over 50 m. Only this one stretch differs by more than 2 pp.',
        proposedFix: "Optional: ELEV_SOURCE 'gb-1948' = EA LIDAR Composite DTM 1 m (WCS GetCoverage GeoTIFF tiles, EPSG:27700; reader in dem.mjs eaLidar) with the terrain-model settings. Small gain (Vale).",
        sources: [EA] },
      { aspect: 'layout', severity: 'cosmetic',
        game: '5.891 km; within 4.7 m of OSM (mean 1.6 m, worst at Aintree); racing direction correct (100 %).',
        real: 'en.wikipedia infobox: Arena Grand Prix Circuit (2010 with the old pits, 2011-present with the Wing), 5.891 km; OSM relation 51160 lap 5891.1 m.',
        proposedFix: 'None.',
        sources: [OSM('gb-1948', 'relation 51160'), 'en.wikipedia.org/wiki/Silverstone_Circuit'] },
    ],
    correction: {
      startAt: { 'gb-1948': [52.0682609, -1.0234867], alternativeStartLine: [52.0693366, -1.0221521], seasons: '2011-2026 (2010 used the National Pit Straight = the current game line)' },
      pitFacts: { 'gb-1948': { side: -1 } },
      sceneryNotes: 'Wing building as pit kind; add the Wellington Straight bridges and the Wing glass footbridge (building=bridge, min_height 14.5 m)',
      elevationSource: { id: 'ealidar', optional: true, label: 'Environment Agency LIDAR Composite DTM 1 m (Open Government Licence)', service: 'https://environment.data.gov.uk/spatialdata/lidar-composite-digital-terrain-model-dtm-1m/wcs?service=WCS&version=2.0.1&request=GetCoverage&CoverageId=13787b9a-26a4-4775-8523-806d13af58fc__Lidar_Composite_Elevation_DTM_1m&format=image/tiff&subset=E(x0,x1)&subset=N(y0,y1)', crs: 'EPSG:27700 (British National Grid; Helmert WGS84 -> OSGB36 in lib.mjs toBNG, ~3-5 m)', tiff: 'Float32, tiled 512, georeference in ModelTransformationTag (34264)' },
    },
    sources: [OSM('gb-1948', 'relation 51160'), 'en.wikipedia.org/wiki/2011_British_Grand_Prix', 'en.wikipedia.org/wiki/Silverstone_Circuit', EA],
  },
};
